### ISSUE TITLE
Report Portal client fail to find that a test is running

### ISSUE THREAD

**Issue by Formartha** [reportportal/agent-python-pytest#102]
Hi,

RP client failed to find a test is running. however, with using -p no:pytest_reportportal, the tests works.
my test setup combined from an external parameters I'm pushing and conftest is parsing it.

Any idea what shall I do next?

--EDIT--
I see that the options loaded happnes after the plugin is loaded, that's why It's not getting to the point where it could parse the object I'm sending in as a mandatory part.

**Comment by iivanou** [comment]
@Formartha are you still waiting for a change in the pytest agent side? If so, could you please provide a little bit more details regarding a specific of your tests.

**Comment by HardNorth** [comment]
Abandoned.
