### ISSUE TITLE
Tests results are not present in "Launches"

### ISSUE THREAD

**Issue by rcatz** [reportportal/agent-python-pytest#106]
When I run my tests with pytest.ini for demo server (http://web.demo.reportportal.io) everything work perfect. When I modified the pytest.ini to work with my server - nothing present in "Launches" page.
What could be the reason?

**Comment by rcatz** [comment]
When I run my tests with pytest.ini for demo server (http://web.demo.reportportal.io) everything work perfect. When I modified the pytest.ini to work with my server - nothing present in "Launches" page.
What could be the reason?

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors ^

@rcatz could you plz share any log, you getting from you local execution?

**Comment by iivanou** [comment]
@rcatz Are you still experiencing the problem with reporting?

**Comment by iivanou** [comment]
Closed until the author decides to open it again.
