### ISSUE TITLE
upload image to report

### ISSUE THREAD

**Issue by trew100** [reportportal/agent-python-pytest#107]
I try to upload image to report
so the example in the agent-python doc is about text file and it works well
```python
import subprocess
    free_memory = subprocess.check_output("free -h".split())
    rp_logger.info(
        "Case1. Memory consumption",
        attachment={
            "name": "free_memory.txt",
            "data": free_memory,
            "mime": "application/octet-stream",
        },
    )
```

but if you want to upload image there is a problem
in the `data` key do you can't pass the path to the file because the path pass as a string to report portal, if you change the `mime` to `image/png` do you get 5000 code error (the data will be upload but the report portal can't load the file)

after investigation the way that it works for me is to load the file as a file, like this
```python
with open(screenshot_file_path, "rb") as image_file:
        screenshot_file_path = image_file.read()
rp_logger.info("Some Text Here",
                       attachment={"name": "test_name_screenshot.png",
                                             "data": screenshot_file_path,
                                             "mime": "image/png"})
```

it will be nice to document this

**Comment by krasoffski** [comment]
Yes it is,
`[python-client](https://github.com/reportportal/client-Python/blob/64550693ec9c198b439f8f6e8b23413812d9adf1/reportportal_client/service.py#L259)` uses `request` library for working with RP and the same semantics to work with attachments.

There is two ways to pass data as attachment:

### Case 1 - pass file-like object
```
with open(screenshot_file_path, "rb") as image_file:
    rp_logger.info("Some Text Here",
                            attachment={"name": "test_name_screenshot.png",
                                                 "data": image_file,
                                                 "mime": "image/png"})
```

### Case 2 - pass file content itself (like you did)
```
with open(screenshot_file_path, "rb") as image_file:
        file_data = image_file.read()

rp_logger.info("Some Text Here",
                       attachment={"name": "test_name_screenshot.png",
                                             "data": file_data,
                                             "mime": "image/png"})
```

**Comment by nagarjunakappurapu** [comment]
When execute more than two methods using pytest ,screenshot are sending to only for the first method .

For second method only log message is sending  without screenshot

**Comment by nagarjunakappurapu** [comment]
Can anyone help me about how to resolve the issue
