### ISSUE TITLE
install the agent from git return unexpected keyword argument verify_ssl error

### ISSUE THREAD

**Issue by trew100** [reportportal/agent-python-pytest#111]
step to reproduce 
1. Install the agent from the current  git (1.0.4)
2. ran tests

```
pytest project-tests\tests\suit_basic_tests.py --reportportal
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\main.py", line 207, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\plugin.py", line 57, in pytest_sessionstart
INTERNALERROR>     verify_ssl=session.config.getini('rp_verify_ssl')
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\service.py", line 96, in init_service
INTERNALERROR>     verify_ssl=verify_ssl
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'verify_ssl'```

**Comment by CoRfr** [comment]
It looks like it depends on some changes from https://github.com/reportportal/client-Python such as https://github.com/reportportal/client-Python/commit/d8773d22ce8ebda0ee8c2f0f854192a8a2710364

Problems is that this change is not in a version of client-Python just yet. The latest release (3.2.1) is just before the verify SSL change was introduced.

It looks like pytest-reportportal-1.0.5 was made available on May 10th (https://pypi.org/project/pytest-reportportal/), although the tag is weirdly not available on this repository yet.
It brings reportportal-client-3.2.0 with it (latest release available on https://pypi.org/project/reportportal-client/ ), while it's not actually compatible with this version.

I'm gonna go back to 1.0.4 for now, but to me the latest version as published on https://pypi.org/project/pytest-reportportal/ is broken, and I'm also wondering 3 questions:
- where is 1.0.5 coming from ?
- where is 3.2.1 of https://github.com/reportportal/client-Python on pypi ?
- when is the next release of https://github.com/reportportal/client-Python ?

**Comment by alderven** [comment]
Have same error.
Downgrade [pytest-reportportal](https://pypi.org/project/pytest-reportportal/) to 1.0.4 helped.

**Comment by iivanou** [comment]
@trew100, the dependency in the reportportal-client was resolved yesterday. Can you try a new(3.2.3) version and close the issue if it's not the case anymore? Thanks.
