### ISSUE TITLE
Pytest agent logs item's messages into RP in a force manner

### ISSUE THREAD

**Issue by iivanou** [reportportal/agent-python-pytest#133]
If your project uses Python logging, the Pytest agent forcible catches its messages and sends those to RP. The agent should be extended the way that it allows to disable log messages upload to RP or, at least, make it possible to set up a log level for message to be uploaded. Simple use case: it does not make sense to store test logs in RP if I have them being stored in Jenkins.

**Comment by dijital20** [comment]
Here's a workaround for now. It's not pretty, but it appears to work.

```python
@pytest.fixture(autouse=True)
def squelch_rp_logging():
    """Turn down the RP logging to an appropriate volume."""
    for handler in logging.getLogger().handlers:
        if isinstance(handler, RPLogHandler) and handler.level != logging.INFO:
            LOG.info('Setting %r to INFO', handler)
            handler.setLevel(logging.INFO)
            LOG.debug('This should not be visible')
````

**Comment by iivanou** [comment]
I thought of a new option for the pytest.ini. Thanks for the input.

**Comment by dijital20** [comment]
Oh, I agree. Adding an ini option would be far better. What I was proposing was a workaround until an ini option is available.

**Comment by dijital20** [comment]
I did some digging through the code and found that this ini setting can be set:

```ini
rp_log_level = INFO
```

This appears to squelch the logging at the handler.

**Comment by iivanou** [comment]
This option allows for changing the log level of the RP logger. What I requested is to disable that logger completely with the help of a new option.

**Comment by HardNorth** [comment]
I believe there should be a way to configure that with standard logging mechanism. I'll seek for examples.

**Comment by HardNorth** [comment]
Actually I don't see any RP logs in the latest agent version, everything what appears on Report Portal in our examples is logged by these examples, the same for console. But I created an additional example how to specifically mute Report Portal loggers for those who still see the issue: https://github.com/reportportal/examples-python/tree/master/pytest/tests/muted_logger

I believe no any additional code required, we are using standard Python logging framework and should configure it with standard instruments.
