### ISSUE TITLE
verify_ssl=False no longer works with client v3.2.2+ as of plugin v1.0.8

### ISSUE THREAD

**Issue by cicconej** [reportportal/agent-python-pytest#134]
https://github.com/reportportal/agent-python-pytest/pull/116 commented out the `verify_ssl` argument that `PyTestServiceClass.init_service()` was passing through to `ReportPortalServiceAsync()`, which I think was done to address https://github.com/reportportal/agent-python-pytest/issues/111 and https://github.com/reportportal/agent-python-pytest/issues/112.

However, I think the underlying issue was just that the required `reportportal-client` version was left as `>=3.1.0` when the `verify_ssl` changes were introduced, when it should've been bumped up to `>=3.2.2`.

Since then, the required client version was bumped up even beyond that to `reportportal-client>=3.2.3`, so I believe it should be possible to restore the `verify_ssl` argument that was commented out.

**Comment by iivanou** [comment]
@cicconej Can you create a new PR in order to restore that functionality?

**Comment by cicconej** [comment]
Thank you for the fix, @iivanou.

I saw your comment yesterday asking if I could submit a PR with the fix, and I was actually planning to do that, but I needed to get approval from my workplace to contribute to this project first. I got the approval now, but see you beat me to the fix 😄

Hopefully I'll be able to contribute something else soon!
