### ISSUE TITLE
Print url for launch in console

### ISSUE THREAD

**Issue by zeburek** [reportportal/agent-python-pytest#142]
Actually after running tests with reportportal I couldn't achieve launch from console/CI logs. I should go to RP and find it by myself.

I've added a little bit of code in order to make this work:

![image](https://user-images.githubusercontent.com/20853475/68474845-938a6980-0237-11ea-98f7-18b90816989c.png)

**Comment by evjlobanova** [comment]
@reportportal/python-contributors

**Comment by iivanou** [comment]
This issue is waiting for unit tests to be added to #143 by @zeburek.

**Comment by HardNorth** [comment]
I've already implemented an example how anyone can get a launch URL and print it to Report Portal and in console:
https://github.com/reportportal/examples-python/blob/master/pytest/tests/test_launch_url_get.py

I believe this is completely closes the question. And it doesn't require any agent update. Moreover not all users might want to see such info in logs, so I don't see any necessity to implement it in agent's code.

**Comment by gernotfeichter** [comment]
Thanks.

However, in the long run I think it would be better to have such code/feature in the agent, since otherwise ppl. need to do many code duplications across their projects.

Also, it would be great if this was implemented across the agents of the various supported programming languages.
