### ISSUE TITLE
INTERNALERROR> KeyError: 'subTypes'

### ISSUE THREAD

**Issue by acdurai** [reportportal/agent-python-pytest#145]
I'm getting below error while try to run the test. Kindly help me to overcome this issue.

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\_pytest\main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pytest_reportportal\plugin.py", line 59, in pytest_sessionstart
INTERNALERROR>     retries=int(session.config.getini('retries')),
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pytest_reportportal\service.py", line 104, in init_service
INTERNALERROR>     self.issue_types = self.get_issue_types()
INTERNALERROR>   File "c:\users\cayyanar.cccis\mobile_automation\venv_test\lib\site-packages\pytest_reportportal\service.py", line 307, in get_issue_types
INTERNALERROR>     for item in self.project_settings["subTypes"][item_type]:
INTERNALERROR> KeyError: 'subTypes'

**Comment by iivanou** [comment]
@acdurai Could you please share with us the outcome of the following request:
curl -X GET --header 'Authorization: bearer YOUR_TOKEN_HERE' https://YOUR_RP_URL/api/v1/YOUR_PROJECT_NAME/settings

**Comment by acdurai** [comment]
@iivanou . Thanks for your prompt response. 

The script is working fine now. The reason for the failure is , by mistake extra characters added at the end of UDID value, because of this the testscript got failed. 


rp_uuid=e6e17009-d751-42ee-b47e-bba4910d8d6c

**Comment by iivanou** [comment]
@acdurai glad to be useful:)
