### ISSUE TITLE
rp_logger.py are not creating attachment object after first test is run.

### ISSUE THREAD

**Issue by ohank** [reportportal/agent-python-pytest#154]
I am logging and attaching a txt fil after all tests. but after the first one is done the logger churches on that it don't find the attachment in LogRecord object.

I have tried to remove allure and all the pycache files to. but the same result.

request = &lt;SubRequest 'rp_additional_data' for &lt;Function test_tm_074&gt;&gt;, rp_logger = &lt;RPLogger test_framework.plugins.report_portal (INFO)&gt;
environment = &lt;test_framework.environment._environment.Environment object at 0x7f51e5ba3b38&gt;, rig = &lt;lhd_test.common.lhd_machine.LhdMachine object at 0x7f521e2690b8&gt;

    @pytest.fixture(scope='function', autouse=True)
    def rp_additional_data(request, rp_logger, environment, rig):
        """
        Fixture for add sysconf, parallel index, and remaining events after the test is run.
        :param request: Pytest object that contains data of the test session.
        :param rp_logger: Fixture enabling sending test results to report portal.
        :param environment: Environment fixture that contains machine configuration.
        :param rig: The rig object for the machine.
        :return: None
        """
        if not request.config.getoption('pytest_reportportal'):
            yield # must yield once before return from fixture
            return
    
        yield
        for machine_tag, machine_indices in environment.available_machines().items():
            for machine_index in machine_indices:
                # Sysconf
                sysconf_path = environment.sysconf_path(machine_tag, machine_index)
                with open(str(sysconf_path)) as fp:
                    rp_logger.info(
                        'Sysconf: ' + str(sysconf_path),
                        attachment={
                            'name': 'sysconf{}.txt'.format(machine_tag),
                            'data': fp.read(),
&gt; 'mime': 'application/octet-stream'}
                    )

lhd_auto_test/test_automation/pythontests/test_framework/src/test_framework/plugins/report_portal.py:79:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.6/logging/__init__.py:1308: in info
    self._log(INFO, msg, args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;RPLogger test_framework.plugins.report_portal (INFO)&gt;, level = 20, msg = 'Sysconf: lhd/Config/ST14/70_Autonomous/SysConf.txt', args = (), exc_info = None, extra = None, stack_info = False
attachment = {'data': '!=== Prepared by: sysConfGen.py ==\n!=== Created: 2019-12-18 09:11:50 ==\n!== Software Part No: 9999 4200 ...N 1\nCHECKSUM 92329BB3\n', 'mime': 'application/octet-stream', 'name': 'sysconfrig.txt'}

    def _log(self, level, msg, args,
             exc_info=None, extra=None, stack_info=False, attachment=None):
        """
        Low-level logging routine which creates a LogRecord and then calls
        all the handlers of this logger to handle the record.
        """
        sinfo = None
        if logging._srcfile:
            # IronPython doesn't track Python frames, so findCaller raises an
            # exception on some versions of IronPython. We trap it here so that
            # IronPython can use logging.
            try:
                if PY2:
                    # In python2.7 findCaller() don't accept any parameters
                    # and returns 3 elements
                    fn, lno, func = self.findCaller()
                else:
                    fn, lno, func, sinfo = self.findCaller(stack_info)
    
            except ValueError: # pragma: no cover
                fn, lno, func = '(unknown file)', 0, '(unknown function)'
        else:
            fn, lno, func = '(unknown file)', 0, '(unknown function)'
    
        if exc_info and not isinstance(exc_info, tuple):
            exc_info = sys.exc_info()
    
        if PY2:
            # In python2.7 makeRecord() accepts everything but sinfo
            record = self.makeRecord(self.name, level, fn, lno, msg, args,
                                     exc_info, func, extra)
        else:
            record = self.makeRecord(self.name, level, fn, lno, msg, args,
                                     exc_info, func, extra, sinfo)
    
&gt; if not record.attachment:
E AttributeError: 'LogRecord' object has no attribute 'attachment'

/usr/local/lib/python3.6/dist-packages/pytest_reportportal/rp_logging.py:47: AttributeError

**Comment by iivanou** [comment]
@ohank already fixed in #131 .

**Comment by ohank** [comment]
Is this fix in the docker compos i can get from https://reportportal.io/download or do i have to wait for a new version?

**Comment by iivanou** [comment]
@ohank You should update your Python Pytest agent.

**Comment by ohank** [comment]
I have the latest pytest and pytest-reportportal. is Python Pytest agent something else?

**Comment by iivanou** [comment]
@ohank Oh, these changes have not been released yet. We are gonna release 1.0.9 version of the agent day on day. Please keep track of updates on the list of releases.

**Comment by ohank** [comment]
Ok, then I wait for the release. Thank for the help.
