### ISSUE TITLE
AttributeError: 'PyTestServiceClass' object has no attribute 'issue_types'

### ISSUE THREAD

**Issue by tqu007** [reportportal/agent-python-pytest#155]
/usr/local/bin/python3.8 /Users/timq/xxx/xxx/runsuite.py
============================= test session starts ==============================
platform darwin -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/timq/rcc/rcc_api_test, inifile: pytest.ini
plugins: reportportal-1.0.8
collecting ... collected 84 items

tests/mega/account/test_account.py::TestFreeSubscribersSearch::test_free_subs_search_default PASSED [  1%]
tests/mega/account/test_account.py::TestFreeSubscribersSearch::test_free_subs_search_like PASSED [  2%]
tests/mega/account/test_account.py::TestFreeSubscribersSearch::test_free_subs_search_order PASSED [  3%]
tests/mega/common/test_collections.py::TestCommonCollections::test_add_collections 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 196, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 96, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 184, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/listener.py", line 78, in pytest_runtest_makereport
INTERNALERROR>     self._add_issue_info(item, report)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/listener.py", line 115, in _add_issue_info
INTERNALERROR>     if issue_type and self.PyTestService.issue_types \
INTERNALERROR> AttributeError: 'PyTestServiceClass' object has no attribute 'issue_types'

========================= 3 passed, 1 warning in 1.02s =========================

Process finished with exit code 0

**Comment by tqu007** [comment]
rccdeMacBook-Pro:rptest timq$ pytest test_rp.py
============================================================================ test session starts =============================================================================
platform darwin -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/timq/rcc/qa/rptest, inifile: pytest.ini
plugins: reportportal-1.0.9
collected 2 items

test_rp.py::test_gui PASSED                                                                                                                                            [ 50%]
test_rp.py::test_api PASSED                                                                                                                                            [100%]

============================================================================= 2 passed in 0.01s ==============================================================================
rccdeMacBook-Pro:rptest timq$ pytest test_rp.py --reportportal
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 194, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/plugin.py", line 45, in pytest_sessionstart
INTERNALERROR>     session.config.py_test_service.init_service(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/service.py", line 117, in init_service
INTERNALERROR>     self.issue_types = self.get_issue_types()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/service.py", line 348, in get_issue_types
INTERNALERROR>     for item in self.project_settings["subTypes"][item_type]:
INTERNALERROR> KeyError: 'subTypes'

**Comment by iivanou** [comment]
@tqu007 Check your project name and authorization token are correctly configured. Run from the console:

> curl --header 'Authorization: bearer YOUR_TOKEN_HERE' https://YOUR_RP_ADDRESS/api/v1/YOUR_PROJECT_NAME/settings

You should get a response similar to the below one, otherwise - you missed somewhere. Valid response should include the subTypes key.

> {"project":2389,"**subTypes**":{"NO_DEFECT":[{"id":4,"locator":"nd001","typeRef":"NO_DEFECT","longName":"No Defect","shortName":"ND","color":"#777777"}],"TO_INVESTIGATE":[{"id":1,"locator":"ti001","typeRef":"TO_INVESTIGATE","longName":"To Investigate","shortName":"TI","color":"#ffb743"}],"AUTOMATION_BUG":[{"id":2,"locator":"ab001","typeRef":"AUTOMATION_BUG","longName":"Automation Bug","shortName":"AB","color":"#f7d63e"}],"PRODUCT_BUG":[{"id":3,"locator":"pb001","typeRef":"PRODUCT_BUG","longName":"Product Bug","shortName":"PB","color":"#ec3900"}],"SYSTEM_ISSUE":[{"id":5,"locator":"si001","typeRef":"SYSTEM_ISSUE","longName":"System Issue","shortName":"SI","color":"#0274d1"}]}}

**Comment by tqu007** [comment]
it works now. thanks @iivanou

**Comment by tqu007** [comment]
@iivanou thanks, it works fine after i regenerated the key and updated config file.

**Comment by iivanou** [comment]
You are welcome!
