### ISSUE TITLE
add the ability to specify launch_id

### ISSUE THREAD

**Issue by ainur-fa** [reportportal/agent-python-pytest#156]
to send reports to an already launched launcher add the ability to specify argument launch_id

**Comment by iivanou** [comment]
@ainur-fa Could you please elaborate on a use case for this request? It does not seem to be a good idea to report to existing launch from multiple places.

**Comment by ainur-fa** [comment]
I expect the following:
1) create launch on reportportal (by jenkins)
2) run the test suite in parallel on several remote hosts.
    all remote hosts must report to a pre-opened launch.
3) the launcher closes (by jenkins)

with steps 1, 3, everything seems clear,
for step 2, I suppose to pass the "launch_id" received in step 1
example:

`pytest test_suite1.py --rp_launch_id=5e26d2f3b3cb1f00010eb2a6`
or
```
#  pytest.ini
[pytest]
addopts = --reportportal
rp_uuid = 04fdd5af-432d-4126-a68b-fbe56dea3155
rp_endpoint = http://192.168.1.10:80
rp_project = project_name
rp_launch = test_suite1
rp_launch_id = 5e26d2f3b3cb1f00010eb2a6
```

**Comment by iivanou** [comment]
@ainur-fa Why don't you run your tests in parallel on the single remote host by Jenkins? You can execute you test simultaneously with the xdist Pytest plugin.

**Comment by ainur-fa** [comment]
the fact is that tests run on machines with different operating systems and with different configurations.

**Comment by iivanou** [comment]
It's not a good idea to report tests started on different environments to the common launch from testing philosophy point of view. You **launch** tests on the remote environment and should report results to a separate **launch**.  @DzmitryHumianiuk any comments on this?

**Comment by ainur-fa** [comment]
from the point of view of the testing philosophy, I don’t see any problems either, these are the same test suites only on different operating systems, and inside the launcher the results from different operating systems will differ by tags

**Comment by iivanou** [comment]
What you are requesting is an ability to report launches to the common launch. When you are starting any kind of test framework on any environment means you are starting a launch.

**Comment by DzmitryHumianiuk** [comment]
>It's not a good idea to report tests started on different environments to the common launch from testing philosophy point of view. You launch tests on the remote environment and should report results to a separate launch. @DzmitryHumianiuk any comments on this?

well, i don't see any issue here. There are 2 most common approaches:
- separate executions from various envs with Launches
- put all envs in one launch, to see summary statistics

In first case - there is a summary charts like (overall statistics) for the group of launches.
in seconds case, if project don't need such details as stability on particular type of env - this will be more preferable and easy to use, regards widgets and visualisation.

But here, i would refer to the main idea, which we following right now, and will use in version6 of report portal - **forget about launches and build everything around tests first**.
Here i mean that all widgets will be focused on test cases first, and the grouping/filtering capabilities will be realized via the attributes. 
Launch will still be there, cause it physically represents session of execution, from start moment till end, it will be used as a logical container for tests, to inherit attributes from upper level down to each test case.
Like if you started tests against MacOs and Safari and added this as attribute to the launch -> all tests will inherit this attribute from it.

This approach basically means that launches will not have any meaningful purpose, only as container.
And all visualizations will be based on tests and how they filtered/grouped.
The only reason to keep them is just the usual way for engineers to find results of execution.

Therefore there will be no difference how to collect Launches, **but only in version 6**

As for actual version (5.x+) we gave possibility to collect multi-threaded launches in one out of the box.
`client-java` starting v5 and RPv5 has capabilities to merge test structures in runtime.
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch
The same principle we expect to appear in every client as well.

This capability can help to:
- merge in runtime multi-threaded launches into one launch  (any sort of multi-threading)
- merge in runtime multi-threaded launches from physically separate machines
- re-run results of specified launch (re-executed test cases will be replaces with re-tries)
- re-run portion of results to specified (or just latest launch)

These 2 issues were in top 3 queries for ReportPortal in last 2 years.

docs for reference:
**Configure launch re-run (java example):**
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md
**Configure multi-threaded execution to be collected in one launch (java example):**
https://github.com/reportportal/client-java/wiki/How-to-aggregate-Multi-thread-process-execution-in-one-launch

**Comment by iivanou** [comment]
> Launch will still be there, cause it physically represents session of execution, from start moment till end, it will be used as a logical container for tests.

That's what I mean. Launch physically represents the session of execution. The request is about to add an ability to report multiple physical executions(session, launches) to the same launch. It can be done by the Pytest framework and the xdist plugin so that the results will be achieved within the **single** session. My point is that in this particular case it would be better to use existing instruments rather than invent the wheel.

**Comment by DzmitryHumianiuk** [comment]
@iivanou will xdist create only one launch for multi-threaded execution? or several of them?

**Comment by iivanou** [comment]
xdist creates only one launch.

**Comment by ajinkyapande** [comment]
Any update on this? 

I also think we need this feature . Lets say , some service is down and tests related to that are failing.
But after some time when the service is up then instead of creating new launcher it will be helpful to have provision to update result in the same laucher

**Comment by iivanou** [comment]
No updates, I haven't seen PRs with implementation. I haven't worked on that enhancement as well.

**Comment by rplevka** [comment]
@iivanou, i think we can close this issue now
