### ISSUE TITLE
How to use this agent when we want to log from a multiprocess Process target func?

### ISSUE THREAD

**Issue by Preyansh91** [reportportal/agent-python-pytest#160]
I am using this agent for my pytest framework and works fine. However can someone please help me understand how to log from multiple methods executing parallely using multiporcessing library? I dont see any logging from the methods in this case to the report portal

**Comment by iivanou** [comment]
@Preyansh91 Have you tried [miltiprocessing logging](https://github.com/jruere/multiprocessing-logging)? Pass rp_logger to the install_mp_handler. RP logger can't catch log messages from spawned processes cause they are being executed in a different context.

**Comment by HardNorth** [comment]
Abandoned
