### ISSUE TITLE
Failed to import ReportPortalServiceAsync

### ISSUE THREAD

**Issue by CodingWander** [reportportal/agent-python-pytest#163]
With the latest release of reportportal_client, we are now starting to see an error:

```
from reportportal_client import ReportPortalServiceAsync
ImportError: cannot import name 'ReportPortalServiceAsync' from 'reportportal_client' (/lib/python3.7/site-packages/reportportal_client/__init__.py)
```

This just started happening with the latest release of the report portal client.

**Comment by iivanou** [comment]
You shouldn't use the latest version of the client with the current version of agents. Please remove reportportal-client version 4.0.0 and **update pytest agent only**.  Agents are aware of the correct version of the client that needs to be installed.
