### ISSUE TITLE
Not able to upload data to report portal, status is displayed as Interrupted

### ISSUE THREAD

**Issue by akki2063** [reportportal/agent-python-pytest#177]
While trying to execute a pytest file, I'm getting below error

command used -- > pytest -m <marker> --reportportal

I'm using pytest.ini in project root folder as below,

[pytest]
rp_uuid=<reportportal token from web profile>
rp_endpoint=http://<docker-ip>:8080
rp_project=<project name>
rp_launch=<Launchname>

After executing and later if i check in reportal portal project, new test will be added with no result (Pass/FAIL/Skipped)...Test will display the file i ran for test and status as interrupted

platform win32 -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: inifile: pytest.ini
plugins: allure-pytest-2.8.12, dependency-0.5.1, reportportal-5.0.0
collected 4 items                                                                                                                                                               
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File \main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File \main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File \lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File \lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File \lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File \lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File \lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File \lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File \lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File \lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File \lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File \lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File \lib\site-packages\pluggy\callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File \lib\site-packages\pytest_reportportal\listener.py", line 41, in pytest_runtes
t_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File \lib\site-packages\pytest_reportportal\service.py", line 240, in start_pytest_
item
INTERNALERROR>     item_id = self.rp.start_test_item(**start_rq)
INTERNALERROR>   File \lib\site-packages\reportportal_client\service.py", line 286, in start_test_it
em
INTERNALERROR>     item_id = _get_id(r)
INTERNALERROR>   File \lib\site-packages\reportportal_client\service.py", line 66, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File \lib\site-packages\reportportal_client\service.py", line 98, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.
ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.uti
l.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
INTERNALERROR>  at [Source: (PushbackInputStream); line: 1, column: 179] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])

Requesting you to help.

**Comment by iivanou** [comment]
@akki2063 What version of the pytest-reportportal agent are u using? What version of the Report Portal are u reporting to?

**Comment by akki2063** [comment]
> @akki2063 What version of the pytest-reportportal agent are u using? What version of the Report Portal are u reporting to?

I'm using 5.0.0 for both pytest-reportportal and web version

**Comment by iivanou** [comment]
Please, do not change the name of the issue, create a new one for a new issue. Update your agent to 5.0.1 version and try again.

**Comment by akki2063** [comment]
> @akki2063 Please, do not change the name of the issue, create a new one for a new issue. Update your agent to 5.0.1 version and try again.

I have updated the pytest agent to 5.0.1 and tested again, but unfortunately same issue persists.

When i execute the command "pytest -m <test-marker> --reportportal" , tests are collected but will not run throwing same error.

INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.
ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.uti
l.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
INTERNALERROR>  at [Source: (PushbackInputStream); line: 1, column: 191] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])

**Comment by iivanou** [comment]
Can you run the Pytest with the following command and share the output:

> pytest --reportportal -s -vv --log-level=DEBUG --log-cli=True <your_test_module>

**Comment by akki2063** [comment]
> pytest --reportportal -s -vv --log-level=DEBUG --log-cli-level=DEBUG

Please find the logs details below...

---------------------------------------------------------------------------- live log sessionstart -----------------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:127 ReportPortal - Init service: endpoint=http://IP:8080, project=test, uuid=b4b41d92-c49c-4790-92d1-daedde908784
DEBUG    urllib3.connectionpool:connectionpool.py:225 Starting new HTTP connection (1): IP:8080
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "GET /api/v1/test/settings HTTP/1.1" 200 676
DEBUG    reportportal_client.service:service.py:364 settings
DEBUG    pytest_reportportal.service:service.py:160 ReportPortal - Start launch: equest_body={'attributes': {'agent': 'pytest-reportportal-pytest-reportportal 5.0.1', 'os': 'Win
dows', 'cpu': 'Intel64 Family 6 Model 142 Stepping 12, GenuineIntel', 'machine': 'AMD64', 'system': True}, 'name': 'AnyLaunchName', 'start_time': '1585829580694', 'description':
 '', 'mode': None}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/test/launch HTTP/1.1" 201 59
DEBUG    reportportal_client.service:service.py:222 start_launch - ID: f9ef266e-06a7-4db1-8140-d70253ab4345
DEBUG    pytest_reportportal.service:service.py:162 ReportPortal - Launch started: id=f9ef266e-06a7-4db1-8140-d70253ab4345
============================================================================= test session starts ==============================================================================
platform win32 -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- <PATH>\python.exe
cachedir: .pytest_cache
rootdir: <PROJECT PATH>, inifile: pytest.ini
plugins: allure-pytest-2.8.12, dependency-0.5.1, reportportal-5.0.1
collected 2 items                                                                                                                                                               
----------------------------------------------------------------------------- live log collection ------------------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:241 ReportPortal - Start Suite: request_body={'name': ':\\tests\
\test_2.py', 'description': None, 'start_time': '1585829580763', 'item_type': 'SUITE', 'parent_item_id': None}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/test/item HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:287 start_test_item - ID: 88051f00-ddfe-4cab-a190-97dbacf5beca
DEBUG    pytest_reportportal.service:service.py:258 ReportPortal - Start TestItem: request_body={'attributes': [{'value': 'api'}], 'name': 'test_gui', 'description': None, 'star
t_time': '1585829580780', 'item_type': 'TEST', 'parent_item_id': '88051f00-ddfe-4cab-a190-97dbacf5beca', 'parameters': {}}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/test/item/88051f00-ddfe-4cab-a190-97dbacf5beca HTTP/1.1" 400 565
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<Project-env>\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "<Project-env>\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<Project-env>\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<Project-env>\lib\site-packages\pluggy\callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "<Project-env>\lib\site-packages\pytest_reportportal\listener.py", line 36, in pytest_runtes
t_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "<Project-env>\lib\site-packages\pytest_reportportal\service.py", line 259, in start_pytest_
item
INTERNALERROR>     item_id = self.rp.start_test_item(**start_rq)
INTERNALERROR>   File "<Project-env>\lib\site-packages\reportportal_client\service.py", line 286, in start_test_it
em
INTERNALERROR>     item_id = _get_id(r)
INTERNALERROR>   File "<Project-env>\lib\site-packages\reportportal_client\service.py", line 66, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File "<Project-env>\lib\site-packages\reportportal_client\service.py", line 98, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.
ws.model.ParameterResource>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.uti
l.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of START_OBJECT token
INTERNALERROR>  at [Source: (PushbackInputStream); line: 1, column: 191] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])
---------------------------------------------------------------------------- live log sessionfinish ----------------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:305 ReportPortal - Finish launch: request_body={'end_time': '1585829580816', 'status': None}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://192.168.99.100:8080 "PUT /api/v1/test/launch/f9ef266e-06a7-4db1-8140-d70253ab4345/finish HTTP/1.1" 200 119
DEBUG    reportportal_client.service:service.py:237 finish_launch - ID: f9ef266e-06a7-4db1-8140-d70253ab4345

**Comment by iivanou** [comment]
Could you try changes from #178?
