### ISSUE TITLE
reportportal_client.errors.ResponseError: 4001: Incorrect Request.

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#181]
Hi
I'm updated to report portal 5.0 and using pytest-reportportal 5.0.2
test run aborted with status:interrupted and the next error in console:
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of
START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of
 START_OBJECT token
INTERNALERROR>  at [Source: (PushbackInputStream); line: 1, column: 200] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])

the same config is fine works with report-portal 4.3

**Comment by iivanou** [comment]
What is the version of Report Portal you are reporting to?

**Comment by dkuchynskyi** [comment]
I report to report portal Build: 5.0.0

**Comment by iivanou** [comment]
Please run your tests with option --log-cli-level=DEBUG and share the output.

**Comment by dkuchynskyi** [comment]
live log collection ------------------------------------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:223 ReportPortal - Start Suite: request_body={'name': ':\\---\\tests\\smoke\\test_cashier.py', 'description': None, 'start_time': '1586166889935', 'item_typ
e': 'SUITE', 'parent_item_id': None}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/---/item HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:287 start_test_item - ID: 5e00579a-b7bd-4e11-87e7-b0052f95ca40
DEBUG    pytest_reportportal.service:service.py:223 ReportPortal - Start Suite: request_body={'name': 'TestCashier', 'description': None, 'start_time': '1586166889969', 'item_type': 'SUITE', 'parent_item_id': '5e0
0579a-b7bd-4e11-87e7-b0052f95ca40'}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/---/item/5e00579a-b7bd-4e11-87e7-b0052f95ca40 HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:287 start_test_item - ID: dec598f7-ba84-4f04-a4e3-ddc3c8fa9df7
DEBUG    pytest_reportportal.service:service.py:239 ReportPortal - Start TestItem: request_body={'name': 'test_18285_add_card_and_deposit', 'description': None, 'start_time': '1586166889994', 'item_type': 'TEST',
'parent_item_id': 'dec598f7-ba84-4f04-a4e3-ddc3c8fa9df7', 'parameters': {}}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "POST /api/v2/---/item/dec598f7-ba84-4f04-a4e3-ddc3c8fa9df7 HTTP/1.1" 400 565
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pluggy\callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pytest_reportportal\listener.py", line 41, in pytest_runtest_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\pytest_reportportal\service.py", line 240, in start_pytest_item
INTERNALERROR>     item_id = self.rp.start_test_item(**start_rq)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\reportportal_client\service.py", line 286, in start_test_item
INTERNALERROR>     item_id = _get_id(r)
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\reportportal_client\service.py", line 66, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File "c:\Users\dmytroku\.virtualenvs\----lo2ya7Tj\lib\site-packages\reportportal_client\service.py", line 98, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of
START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.ta.reportportal.ws.model.ParameterResource>` out of
 START_OBJECT token
INTERNALERROR>  at [Source: (PushbackInputStream); line: 1, column: 200] (through reference chain: com.epam.ta.reportportal.ws.model.StartTestItemRQ["parameters"])
---------------------------------------------------------------------------------------------- live log sessionfinish ----------------------------------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:312 ReportPortal - Finish launch: request_body={'end_time': '1586166890060', 'status': None}
DEBUG    urllib3.connectionpool:connectionpool.py:437 http://IP:8080 "PUT /api/v1/---/launch/1c1939e5-c204-4348-adff-b93f56a13e83/finish HTTP/1.1" 200 16
5
DEBUG    reportportal_client.service:service.py:237 finish_launch - ID: 1c1939e5-c204-4348-adff-b93f56a13e83

**Comment by iivanou** [comment]
Already fixed in 178. Closed.

**Comment by dkuchynskyi** [comment]
But it doesn't work, I'm using 5.0.2

**Comment by iivanou** [comment]
Try removing all the Python cache. Then, make sure that you have pytest-reportportal and reportportal-client packages that are both installed with 5.0.2 versions(other version must be remvoed). If it does not help, share the test code you are running.
