### ISSUE TITLE
[v5]When running test in multiply files test result are show inside the first file

### ISSUE THREAD

**Issue by ohank** [reportportal/agent-python-pytest#182]
Test result reports inside other tests result in a hierarchy.

![image](https://user-images.githubusercontent.com/44366788/78565371-1c74f380-781e-11ea-8ae1-42df06e6d268.png)
![image](https://user-images.githubusercontent.com/44366788/78565415-31ea1d80-781e-11ea-94e6-734f46d81923.png)

And I sorting on fail show no result:
![image](https://user-images.githubusercontent.com/44366788/78565560-6231bc00-781e-11ea-9588-b6c445a43b67.png)
![image](https://user-images.githubusercontent.com/44366788/78565587-6a89f700-781e-11ea-9844-b3f50c9f5033.png)

I am using pytest to run tests and send the result to reportportal. Not sure if this is an agent bug or the web site that is doing anything wrong.

**Expected behavior**
I expected the each file with tests to be group together not all files in the first file.

**Desktop (please complete the following information):**
 - Ubuntu/Windows
 - chrome
 - The version of what? web browser or os?

**Comment by iivanou** [comment]
@ohank Can you try changes from #183? Let us know the results.

**Comment by ohank** [comment]
@iivanou changes from #183 from did fix the problem with nested hierarchy. Still problem show list of pass, skipped. failed and total. But to investigation works. Here are som screenshot:

![image](https://user-images.githubusercontent.com/44366788/78646687-b76edb80-78b9-11ea-85e4-80a2d3bdccc8.png)
![image](https://user-images.githubusercontent.com/44366788/78646740-cc4b6f00-78b9-11ea-819f-73c8e77dcb3e.png)

**Comment by iivanou** [comment]
@ohank Sorry, I do not understand what's wrong on your screenshot...

**Comment by ohank** [comment]
I click the number under PASSED and get that no result is found on the page that opens. 6 test shall be shown in the second screenshot.

**Comment by iivanou** [comment]
Take a look at the URL generated when you click on the PASSED number. It will be similar to `

>item2Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26**filter.in.type%3DSTEP%26**filter.in.status%3DPASSED

If you change STEP to TEST in that URL, you will get what you want. If you think it is an issue, please open it in the reportportal project. It has nothing to do on the agent side. @DzmitryHumianiuk FRom my point of view, it'd be better to fill up the default filter with the TEST item type instead of the STEP one.

**Comment by DzmitryHumianiuk** [comment]
@iivanou that's architectual desicion fail, made 7 years ago.
We named objects corresponding to Test Case as steps, assuming the option to involve BDD.

Now we have nested steps.

And change of STEP type to TEST will affect all variety of our agents, clients and UI as well.
We plan this big step for RP 6.

**Comment by ohank** [comment]
@iivanou I agree with "It has nothing to do on the agent side". It was more that I did report on the reportprotal project, to begin with. Thanks for your help!

@DzmitryHumianiuk It is good you know the problem and has a plan to fix it =)
The thing that is nuclear for me is that in reportportal 4.3 this was working. Have something change in reportportal 5 so this behavior happens based on the architectural decision?

**Comment by DzmitryHumianiuk** [comment]
@ohank where was no big changes for the structure from v4.3 to v5.

Maybe just minor cleans ups from UI side, in order to minimize the move in RPv6.

My suggestion to get it work: change it in client.
Send your tests as type `STEP`.

**Comment by ohank** [comment]
Fix is committed.
