### ISSUE TITLE
[v5] Internal error - empty cpu attribute when running tests in docker

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#184]
Running tests using:
pytest-reportportal==5.0.2
reportportal-client [required: >=5.0.2, installed: 5.0.2]
reporting to Report Portal 5.1.0
Tests run on docker image.
Here is debug log:

/home/jenkins/.local/bin/pipenv run python -m pytest --log-cli-level=DEBUG -m smoke --p grid:mobile --url TARGET-SITE --json-report --reportportal

------------------------------------------------------------------------------------------ live log sessionstart -------------------------------------------------------------------------------------------
DEBUG pytest_reportportal.service:service.py:127 ReportPortal - Init service: endpoint=http://ip:8080, project=new-project, uuid=1efdb247-08a3-4642-9dd3-ad8733346833
DEBUG urllib3.connectionpool:connectionpool.py:225 Starting new HTTP connection (1): CORP-PROXY:8080
DEBUG urllib3.connectionpool:connectionpool.py:437 http://corp-proxy:8080 "GET http://ip:8080/api/v1/new-project/settings HTTP/1.1" 200 676
DEBUG reportportal_client.service:service.py:364 settings
DEBUG pytest_reportportal.service:service.py:160 ReportPortal - Start launch: equest_body={'attributes': {'agent': 'pytest-reportportal-pytest-reportportal 5.0.2', 'os': 'Linux', 'cpu': '', 'machine': 'x86_64', 'system': True}, 'name': 'smoke', 'start_time': '1586248044453', 'description': 'mobile on https://target-site, 'mode': None}
DEBUG urllib3.connectionpool:connectionpool.py:437 http://corp-proxy:8080 "POST http://ip:8080/api/v2/new-project/launch HTTP/1.1" 400 205
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/_pytest/main.py", line 189, in wrap_session
INTERNALERROR> config.hook.pytest_sessionstart(session=session)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in _call_
INTERNALERROR> return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR> firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> return outcome.get_result()
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> raise ex[1].with_traceback(ex[2])
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> res = hook_impl.function(*args)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pytest_reportportal/plugin.py", line 66, in pytest_sessionstart
INTERNALERROR> description=session.config.option.rp_launch_description
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/pytest_reportportal/service.py", line 161, in start_launch
INTERNALERROR> item_id = self.rp.start_launch(**sl_pt)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/reportportal_client/service.py", line 221, in start_launch
INTERNALERROR> self.launch_id = _get_id(r)
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/reportportal_client/service.py", line 66, in _get_id
INTERNALERROR> return _get_data(response)["id"]
INTERNALERROR> File "/home/jenkins/.local/share/virtualenvs/ptts-selenium-winnercom-3oYAHBZ8/lib/python3.7/site-packages/reportportal_client/service.py", line 98, in _get_data
INTERNALERROR> raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.]

In POST: 
{'attributes': {'agent': 'pytest-reportportal-pytest-reportportal 5.0.2', 'os': 'Linux', 'cpu': '', 'machine': 'x86_64', 'system': True}, 'name': 'smoke', 'start_time': '1586248044453', 'description': 'mobile on https://target-site, 'mode': None}

cpu attribute is empty.

**Comment by iivanou** [comment]
Duplicate to https://github.com/reportportal/client-Python/issues/86. Closed.
