### ISSUE TITLE
Design of structured logging in pytest 

### ISSUE THREAD

**Issue by madhukeshava** [reportportal/agent-python-pytest#186]
i need how can log this kind of logging using report logging

![61809146-690dcf80-ae45-11e9-9e5d-b866649d86b6](https://user-images.githubusercontent.com/28648906/78885789-cf418d80-7a7a-11ea-9510-16b937eee6c1.png)
 and is

**Comment by madhukeshava** [comment]
@pytest.fixture(scope="session")
def rp_logger(request):
    import logging
    # Import Report Portal logger and handler to the test module.
    from pytest_reportportal import RPLogger, RPLogHandler
    # Setting up a logging.
    logging.setLoggerClass(RPLogger)
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    # Create handler for Report Portal.
    rp_handler = RPLogHandler(request.node.config.py_test_service)
    # Set INFO level for Report Portal handler.
    rp_handler.setLevesl(logging.INFO)
    logger.addHandler(rp_handler)
    return logger

**Comment by madhukeshava** [comment]
using rplogger fixture

**Comment by iivanou** [comment]
If you implement your steps like Pytest fixtures, it will be possible to report them as test steps via the pytest_fixture_post_finalizer hook: https://docs.pytest.org/en/latest/_modules/_pytest/hookspec.html. It is not currently implemented in the agent. You can either implement it on your own and submit PR or create an issue that will be solved by someone in the future.

**Comment by madhukeshava** [comment]
@iivanou 
we don't have fixture STEP annotation like  in testNG..same way in pytest

**Comment by HardNorth** [comment]
Today I merged 5.1 branch. So now you can use full-functioning Nested Steps.
