### ISSUE TITLE
[v5] No result when click on tests number in launch

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#188]
Report portal v 5.1.0
pytest-reportportal v 5.0.2
1. Go to Launches
2 Click on any tests number (Total, Passed, Failed - no matter)
image
![image](https://user-images.githubusercontent.com/34566341/79210766-fec31200-7e4d-11ea-845c-d982ff9040f4.png)

actual result:
empty page with no results opened:
image
![image](https://user-images.githubusercontent.com/34566341/79210798-0a163d80-7e4e-11ea-9878-b7e7c3edd9d8.png)

Expected result:
list of tests should be present as it was in version 4

releated to https://github.com/reportportal/agent-Python-RobotFramework/pull/57#event-3214823385

**Comment by dkuchynskyi** [comment]
@iivanou @DzmitryHumianiuk Hi guys, is it possible to roll out  v. 5.0.3 now?

**Comment by iivanou** [comment]
@dkuchynskyi 5.0.3 has been released.
