### ISSUE TITLE
TypeError: test() missing 1 required positional argument: 'rp_logger'

### ISSUE THREAD

**Issue by RakeshSharma04** [reportportal/agent-python-pytest#193]
Hi, 
Implementing the rp_logger as described, Added rp_logger fixture in conftest and the simply called rp_logger in test method as test(self, rp_logger) but getting the error TypeError: test_validLoginLogout() missing 1 required positional argument: 'rp_logger'

**Comment by iivanou** [comment]
@RakeshSharma04 Are you using unittest.TestCase in your test classes?

**Comment by RakeshSharma04** [comment]
yes 
@pytest.mark.usefixtures("oneTimeSetUp")
class LoginTests(unittest.TestCase):

**Comment by iivanou** [comment]
Pytest fixtures do not work in classes inherited from unittest.TetsCase: https://docs.pytest.org/en/latest/unittest.html.

**Comment by RakeshSharma04** [comment]
Thanks, @iivanou, what else can be done to avoid this...., pretty new to python and pytest.

**Comment by iivanou** [comment]
Have you read the given article till the end? https://docs.pytest.org/en/latest/unittest.html#mixing-pytest-fixtures-into-unittest-testcase-subclasses-using-marks

**Comment by RakeshSharma04** [comment]
I am removing unitets.TestCase, it is not collecting the test items

**Comment by RakeshSharma04** [comment]
> Have you read the given article till the end? https://docs.pytest.org/en/latest/unittest.html#mixing-pytest-fixtures-into-unittest-testcase-subclasses-using-marks
> 
> Or you can re-write your tests without unittest.TestCase.

Thanks got it
