### ISSUE TITLE
Slow test execution

### ISSUE THREAD

**Issue by nbob31** [reportportal/agent-python-pytest#196]
When running selenium tests locally with reportportal enabled there is signification degradation. Tests are extremely slow where the execution difference is 2 minutes compared to reportportal not enabled. I have ran tests using xdist for threading and a single test without multiple processes and the result is the same. It seems that there is a lag or wait before each test action is executed. 

```
rp_project = webtest_demo
rp_launch = Webtests
rp_launch_attributes = 'PyTest' 'Smoke'
rp_tests_attributes = 'PyTest' 'Smoke'
rp_launch_description = 'WebTest Suite'
rp_ignore_errors = True
rp_ignore_tags = 'xfail' 'usefixture'
rp_hierarchy_dirs = True
rp_hierarchy_module = True
rp_hierarchy_class = True
rp_display_suite_test_file = True
rp_hierarchy_dirs_level = 0
rp_verify_ssl = true
rp_log_batch_size = 20
rp_hierarchy_parametrize = True
```
**NOTE**
If I set `rp_log_level = INFO` the execution time is normal.

OS: MAC
Browser: Chrome
ReportPortal: 5.1.0 on Kubernetes
pytest-reportportal 5.0.3
pytest 5.4.1
pytest-xdis 1.31.0
Python 3.8.0

**Comment by iivanou** [comment]
@nbob31 How many screenshots made by Selenium do you upload to RP? When you set rp_log_level to INFO, Selenium screenshots are not gonna be uploaded. Despite the fact that the current implementation of the reportportal-client does not support non-blocking HTTP requests, you will notice differences between executions with screenshots(DEBUG level) and without them. Selenium makes a huge amount of screenshots forcing the client to send them to RP via HTTP which introduces a level of slowness in your tests.

**Comment by nbob31** [comment]
Currently no screenshots were being uploaded and it was slow the only performance improvement I saw was setting the log level to info. I noticed when log level was set to DEBUG it was logging a significant amount from selenium.

**Comment by iivanou** [comment]
It is slow 'cause the agent uses requests library in addition to Selenium. We are aware of the fact that the client does not support non-blocking HTTP requests. However, doing requests in the background will add the level of slowness in your tests in any case taking into account the number of logs produced by Selenium. You can create your own logger the way it is done in the rp_logger fixture and customize it the way you need it. The fixture described in the documentation is just an example.

**Comment by nbob31** [comment]
Is there away to limiting logging of all requests when the log level is set to debug?

**Comment by nbob31** [comment]
@iivanou I was able to filter out the selenium logs with this setting configuration which reduced the test execution time. 
```
urlliblogger.addHandler(logging.NullHandler)
urlliblogger.propagate = False

seleniumlogger.addHandler(logging.NullHandler)
seleniumlogger.propagate = False
```
