### ISSUE TITLE
Feature request: parametrize test description

### ISSUE THREAD

**Issue by ritchiesinger** [reportportal/agent-python-pytest#198]
Searching source code of agent I found:

    @staticmethod
    def _get_item_description(test_item):
        if isinstance(test_item, (Class, Function, Module, Item)):
            doc = test_item.obj.__doc__
            if doc is not None:
                return trim_docstring(doc)
        if isinstance(test_item, DoctestItem):
            return test_item.reportinfo()[2]

In my tests I use parametrized test functions and I have personal description for each test-case.
If my understanding is correct - there is no way to set description exept docstring, and is common for all test cases which parametrized on one test function? 

And there is no way to override or disable usage of docstring as description? 

I use docsting in my code as it's basicaly used to - as function description, not as a test-case description, and will be a great when I can set test-case description dynamicaly someway (for example like Allure does with "dynamic" methods)

**Comment by iivanou** [comment]
@ritchiesinger Everything's possible with Python. You can write your own implementation of the _get_item_description method and replace the existing method with it. Example:

```
@pytest.hookimpl(trylast=True)
def pytest_collection_finish(session):
    
    def _custom_item_description(item=None):
        return ''

    session.config.py_test_service._get_item_description = _custom_item_description
```

**Comment by ritchiesinger** [comment]
Thanks for the advice. I was able to solve my problem, although I was hoping for a more native way.
