### ISSUE TITLE
Execution time grown from RP v4 to RP v5

### ISSUE THREAD

**Issue by zeburek** [reportportal/agent-python-pytest#204]
Previously I was using a fork of your repo to connect to RP v4 (4.3.6)
The configuration of RP v4 client was:
- agent-python-pytest.git@1.1.3 (from https://github.com/zeburek/agent-python-pytest)
- client-Python.git@3.2.3 (from https://github.com/reportportal/client-Python.git)

Result of execution all API tests was like this:
![image](https://user-images.githubusercontent.com/20853475/84119371-ee3dab00-aa3c-11ea-95cc-11c674d8b231.png)

Now, bumping versions of plugin and client to:
- pytest-reportportal==5.0.3
- reportportal-client==5.0.3
Server Build: 5.2.2

I get slowing down the tests at x2 or more.
![image](https://user-images.githubusercontent.com/20853475/84119465-12998780-aa3d-11ea-831f-e460c2924d04.png)

I stopped tests at the middle at the run, and I'm sure that 1500+ wouldn't complete in past 10 minutes.

Are there any plans to speed up the execution after removing async client?

**Comment by zeburek** [comment]
Also difference without and with RP on 20 tests:
```
20 passed in 15.76s
```

```
20 passed in 26.61s
```

**Comment by iivanou** [comment]
@zeburek latest version of the agent and the client do not support RP v4. Please, read through the documentation and consider using the old one client for reporting to RP v4.

**Comment by zeburek** [comment]
I use new v5 server, sorry, didn't describe this in ticket

**Comment by iivanou** [comment]
Test time growth is expected because in RP v5 we must wait for the API request to complete and return test item UUID in order to handle item hierarchy properly.  This issue will be fixed in a new client that is in development right now.

**Comment by zeburek** [comment]
> This issue will be fixed in a new client that is in development right now.

Do you have any deadline for it?
When we could use it?

**Comment by iivanou** [comment]
> Do you have any deadline for it?
I do not. We work on it in our free time.

**Comment by zeburek** [comment]
Is there any way to help you to speed up this proccess?

We want to use RPv5, but this bug blocks us

**Comment by iivanou** [comment]
> We want to use RPv5, but this bug blocks us

Why can't u use RPv5 right now? The client works but a bit slower...

**Comment by zeburek** [comment]
50 minutes VS 80+ minutes - to much difference

**Comment by iivanou** [comment]
You can implement non-blocking HTTP queries to the API in the client in order to solve the issue with performance.

**Comment by evjlobanova** [comment]
@zeburek ReportPortal team does `t have a dedicated Python developer in the team.
So that we will be glad if you want to contribute us, and help Ivan with agent/client update.
This is the only way to speed up the process

**Comment by 0xIslamTaha** [comment]
@iivanou thnx for your effort. I'm wondering if there is any progress in this issue?

**Comment by HardNorth** [comment]
@0xIslamTaha, @zeburek could you please check that on the latest `reportportal-client` version (5.1.0)?
