### ISSUE TITLE
Field attributes.value size error with long test names or skipped reason

### ISSUE THREAD

**Issue by g-bon** [reportportal/agent-python-pytest#205]
When running the following testcase

```python
class TestFastModeCreation:
    @pytest.mark.skip("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque pen")
    def test_fast_mode_and_creation_modification_using_ctrl_alt_click(self):
        pass
```

A RP error is raised regarding attributes.value size exceeding 128

```
INTERNALERROR>   File "./venv/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 36, in pytest_runtest_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "./venv/lib/python3.7/site-packages/pytest_reportportal/service.py", line 263, in start_pytest_item
INTERNALERROR>     item_id = self.rp.start_test_item(**start_rq)
INTERNALERROR>   File "./venv/lib/python3.7/site-packages/reportportal_client/service.py", line 289, in start_test_item
INTERNALERROR>     item_id = _get_id(r)
INTERNALERROR>   File "./venv/lib/python3.7/site-packages/reportportal_client/service.py", line 66, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File "./venv/lib/python3.7/site-packages/reportportal_client/service.py", line 98, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.]
```

Shortening the test name or the skip reason solves the issue e.g.

```python
class TestFastModeCreation:
    @pytest.mark.skip("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque pen")
    def test_fast_mode_and_creation(self):
        pass
```

System info:
platform darwin -- Python 3.7.6, pytest-5.4.3, py-1.5.4, pluggy-0.13.1 -- 
metadata: {'Python': '3.7.6', 'Platform': 'Darwin-19.4.0-x86_64-i386-64bit', 'Packages': {'pytest': '5.4.3', 'py': '1.5.4', 'pluggy': '0.13.1'}, 'Plugins': {'xdist': '1.22.3', 'hypothesis': '5.16.1', 'metadata': '1.9.0', 'reportportal': '5.0.3', 'cov': '2.5.1', 'allure-pytest': '2.8.16', 'benchmark': '3.2.2', 'plan': '1.1', 'forked': '1.1.3'}, 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/openjdk-13.0.2.jdk/Contents/Home'}
plugins: xdist-1.22.3, hypothesis-5.16.1, metadata-1.9.0, reportportal-5.0.3, cov-2.5.1, allure-pytest-2.8.16, benchmark-3.2.2, plan-1.1, forked-1.1.3

Using reportportal 5.2

**Comment by iivanou** [comment]
Fixed in the common client through [this](https://github.com/reportportal/client-Python/pull/137) PR.
