### ISSUE TITLE
--reportportal -o "rp_launch_attributes=TestingTags" doesn't tag the launch in ReportPortal

### ISSUE THREAD

**Issue by usr3514** [reportportal/agent-python-pytest#206]
Hi All,

I tried running pytest with --reportportal -o "rp_launch_attributes=TestingTags" command.
It doesn't add the attributes to the test launch.
I also tried -o "rp_launch_attributes=run_id:TestingTags" where 'run_id' is attribute key and 'TestingTags' is attribute value. That doesn't work as well.

I'm using below versions of lib
pytest==5.0.1
pytest-reportportal==5.0.3

Could someone help me resolve this.

**Comment by iivanou** [comment]
@usr3514 Hi, everything works on my side...

![image](https://user-images.githubusercontent.com/8349078/86216686-1d9c8f00-bb87-11ea-920e-fb69ca2317b6.png)

![image](https://user-images.githubusercontent.com/8349078/86216728-28efba80-bb87-11ea-9a1d-3ee396236030.png)

![image](https://user-images.githubusercontent.com/8349078/86216859-52104b00-bb87-11ea-8dd1-2d48e1e5bb08.png)

**Comment by usr3514** [comment]
@iivanou Thank you for responding. 
Its working form me when I run the pytest command with --reportportal -o "rp_launch_attributes=TestingTags"  in command-line.
Earlier i was running pytest with --reportportal -o "rp_launch_attributes=TestingTags" added in pytest.ini file.

**Comment by iivanou** [comment]
Could you please describe what exactly is not working on your side? I'm confused now.

**Comment by usr3514** [comment]
When i raised the issue i was running pytest with --reportportal -o "rp_launch_attributes=TestingTags" added in pytest.ini file (which doesn't work)

![image](https://user-images.githubusercontent.com/39473789/86310800-8134c400-bc3c-11ea-8a34-a976d840dca0.png).

After you responded to the issue I ran pytest with --reportportal -o "rp_launch_attributes=TestingTags"  in commandline, and it worked
![image](https://user-images.githubusercontent.com/39473789/86311078-2e0f4100-bc3d-11ea-8b19-a52cf06b9a35.png)

Thank you

**Comment by dimit999** [comment]
@iivanou u didn't fix all issues

if run in this format: -o "rp_launch_attributes=sanya:krasava"

U WILL SEE THAT TEST WILL NOT ADDED TO WIDGET
TAG WILL NOT CREATE CORRECTLY: IN YOUR CODE U HAVE:

because in your code:
attributes = [{'value': tag} for tag in
                      session.config.getini('rp_launch_attributes')]

if debbug it - it is looks like: value: sanya:krasava

but we need key and value

NOT only value

**Comment by iivanou** [comment]
@dimit999 First of all, I have not fixed anything. Secondly, it is not necessary to use the caps lock. Have you seen somewhere in the documentation that the agent supports sending key/value attributes? I do not think so. If you want to implement that(key/value) functionality, create a new issue as a new feature request and someone will pick it up in the future. This particular issue is not related to your request.
