### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'longrepr'

### ISSUE THREAD

**Issue by EitanBe** [reportportal/agent-python-pytest#218]
latest reportPortal version 5.0.3

**Comment by iivanou** [comment]
@EitanBe Please, use [this handbook](https://musescore.org/ru/handbook/developers-handbook/getting-started/how-write-good-bug-report-step-step-instructions) to create a good issue. It is not possible to move further with the currently given information.

**Comment by EitanBe** [comment]
The issue was an old pytest version.

**Comment by EitanBe** [comment]
update pytest version
