### ISSUE TITLE
Sending data during test execution desync test to fail.

### ISSUE THREAD

**Issue by ohank** [reportportal/agent-python-pytest#221]
Hi, we have a problem that python agent slows down that test execution during a test case.
A test case consists of several asserts after each asserts the python agent sends/receives data to/from report portal services.
This leads to our test case fail due to time sync. 
Is there a way to set communication only at the end of the test case.

**Comment by iivanou** [comment]
The communication with the RP API occurs twice: at the very beginning of the test, and at the end of the test.
