### ISSUE TITLE
pytest-parallel doesnt work with pytest-reportportal

### ISSUE THREAD

**Issue by EitanBe** [reportportal/agent-python-pytest#222]
Environment:
pytest 6.0.1
python 3.7.3
pytest-parallel 0.1.0
reportrportal - latest 

Exception:
plugins: reportportal-5.0.4, parallel-0.1.0, xdist-1.30.0, metadata-1.10.0, sugar-0.9.2, lazy-fixture-0.4.2, shutil-1.7.0, check-0.3.4, html-1.19.0, ordering-0.6, forked-1.3.0, allure-pytest-2.8.6
collecting ... pytest-parallel: 4 workers (processes), 1 test per worker (thread)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 93, in run
INTERNALERROR>     run_test(self.session, item, None)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 54, in run_test
INTERNALERROR>     item.ihook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 55, in pytest_runtest_protocol
INTERNALERROR>     item_id = self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/pytest_reportportal/service.py", line 297, in start_pytest_item
INTERNALERROR>     item_id = self.rp.start_test_item(**payload)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/reportportal_client/service.py", line 298, in start_test_item
INTERNALERROR>     r = self.session.post(url=url, json=data, verify=self.verify_ssl)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
INTERNALERROR>     return self.request('POST', url, data=data, json=json, **kwargs)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/requests/sessions.py", line 516, in request
INTERNALERROR>     prep = self.prepare_request(req)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/requests/sessions.py", line 459, in prepare_request
INTERNALERROR>     hooks=merge_hooks(request.hooks, self.hooks),
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/requests/models.py", line 317, in prepare
INTERNALERROR>     self.prepare_body(data, files, json)
INTERNALERROR>   File "PATH/v/lib/python3.7/site-packages/requests/models.py", line 467, in prepare_body
INTERNALERROR>     body = complexjson.dumps(json)
INTERNALERROR>   File "PATH.pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 231, in dumps
INTERNALERROR>     return _default_encoder.encode(obj)
INTERNALERROR>   File "PATH.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 199, in encode
INTERNALERROR>     chunks = self.iterencode(o, _one_shot=True)
INTERNALERROR>   File "PATH.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 257, in iterencode
INTERNALERROR>     return _iterencode(o, 0)
INTERNALERROR>   File "PATH.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 179, in default
INTERNALERROR>     raise TypeError(f'Object of type {o.__class__.__name__} '
INTERNALERROR> TypeError: Object of type LocalPath is not JSON serializable

**Comment by iivanou** [comment]
Duplicate to #224.
