### ISSUE TITLE
Add support for the latest xdist versions 2.x

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#225]
Report Portal v 5.3.0
Python 3.8.3,
pytest-6.0.1
pytest reportportal-5.0.3
pytest xdist-2.1.0

running tests with report portal and ixdist causes error:

gw0 C / gw1 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\_pytest\main.py", line 238, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\xdist\dsession.py", line 78, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\xdist\workermanage.py", line 65, in setup_nodes
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\xdist\workermanage.py", line 65, in <listcomp>
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\xdist\workermanage.py", line 73, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\xdist\workermanage.py", line 260, in setup
INTERNALERROR>     self.config.hook.pytest_configure_node(node=self)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\-\.virtualenvs\-\lib\site-packages\pytest_reportportal\plugin.py", line 43, in pytest_configure_node
INTERNALERROR>     node.slaveinput['py_test_service'] = pickle.dumps(node.config.py_test_service)
INTERNALERROR> AttributeError: 'WorkerController' object has no attribute 'slaveinput'

**Comment by iivanou** [comment]
@dkuchynskyi Downgrade pytest to any of 5.x version.

**Comment by dkuchynskyi** [comment]
@iivanou does it mean that bug in pytest?
it is not so easy for my project to downgrade pytest because of other dependencies

**Comment by dkuchynskyi** [comment]
@iivanou the same with pytest 5.4.3
platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1

plugins: forked-1.3.0, json-report-1.2.1, metadata-1.10.0, remotedata-0.3.2, reportportal-5.0.3, xdist-2.1.0

INTERNALERROR>     node.slaveinput['py_test_service'] = pickle.dumps(node.config.py_test_service)
INTERNALERROR> AttributeError: 'WorkerController' object has no attribute 'slaveinput'

**Comment by iivanou** [comment]
@dkuchynskyi Could you try xdist plugin version 1.31? There were a significant amount of changes made in the new major version of these plugins. We're not planning to support them on the first steps until they become not more not less stable.

**Comment by dkuchynskyi** [comment]
@iivanou thanks,
 now it works with next config:
pytest-reportportal = "==5.0.3"
pytest = "==5.4.3"
pytest-xdist = "==1.31.0"

**Comment by iivanou** [comment]
Np. I'll leave this issue as is for the tracking purpose.

**Comment by NoReflexness** [comment]
@pytest.mark.optionalhook
def pytest_configure_node(node):
    """
    Configure node of tests.

    :param node: _pytest.nodes.Node
    :return: pickle of RPService
    """
    if node.config._reportportal_configured is False:
        # Stop now if the plugin is not properly configured
        return
    
    # xdist 2.x support hotfix
    if "slaveinput" in node.__dict__:
        node.slaveinput['py_test_service'] = pickle.dumps(node.config.
                                                      py_test_service)
