### ISSUE TITLE
How to dynamically add Report Portal test attributes to Pytest test

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/agent-python-pytest#229]
First tried asking this on stackoverflow but didn't get any responses.... I'm using the Reportportal Pytest plugin. Is there a way to add test attributes to a test other than using rp_tests_attributes defined in the pytest.ini file (or on the command line). Specifically, my test will learn some information about the "System Under Test" and then perform the test. I want to add a piece of that "learned" information as a ReportPortal test attribute ( or some type of field in ReportPortal where I can later use that information for filtering via the ReportPortal Web interface. Thus, I won't know the value of that attribute until after the test starts.

Thanks Al

**Comment by iivanou** [comment]
It is possible using Pytest markers.

**Comment by allan-silverstein** [comment]
Right, I saw that pytest markers get translated to test attributes.  However, the markers are preset before the test runs.  In my case, the test setup will extract a piece of information from the "System Under Test'.  I then want to make that piece of information sent to report portal and also be searchable/filtered via the Report Portal Web Portal.
Any way to do this?
Thx
Al

**Comment by iivanou** [comment]
Currently, it's impossible because the list of markers is being created before execution starts.

**Comment by allan-silverstein** [comment]
What about if I learn the information I need through a fixture.  The information is then returned to the test function... Any information that can be passed to reportportal that way (and then filtered on)?

**Comment by iivanou** [comment]
Nope, you can do this through the pytest_runtest_protocol hook only.
