### ISSUE TITLE
Log batch size parameter from pytest.ini is ignored.

### ISSUE THREAD

**Issue by NikitaFedoraev** [reportportal/agent-python-pytest#233]
Log batch size parameter from pytest.ini ignored.

https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/service.py#L147
```python
self.rp = ReportPortalService(
                endpoint=endpoint,
                project=project,
                token=uuid,
                retries=retries,
                verify_ssl=verify_ssl
            )
```
`log_batch_size` is not passed to the `ReportPortalService()` constructor.

As result:
1. attachments are not seen in real-time. To see an attachment a user needs to wait till required number of attachments will be in the batch /end of sessions. 
2. With default value 20, an attachment may be attached to the wrong tests (always wrongly attached in my case).  Most probably this is another issue in RP itself.  
And there is a chance that an attachment will not be displayed/lost if a few have the same name. e.g. test1 has `screen1.png` and test2 has `screen1.png`.

1+2 is really inconvenient because forces user to wait long to scroll a few tests forward.

**Comment by NikitaFedoraev** [comment]
In the constructor, we have `self.log_batch_size = 20` which is not used at all. 
Should I set this value to the property to be consistent?

```python
class PyTestServiceClass(with_metaclass(Singleton, object)):
    """Pytest service class for reporting test results to the Report Portal."""

    def __init__(self):
        """Initialize instance attributes."""
        self._agent_name = 'pytest-reportportal'
        self._errors = queue.Queue()
        self._hier_parts = {}
        self._issue_types = {}
        self._item_parts = {}
        self._loglevels = ('TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR')
        self.ignore_errors = True
        self.ignored_attributes = []
        self.log_batch_size = 20   # <- here
        self.log_item_id = None
```

**Comment by iivanou** [comment]
It is missing because that feature is not working right now.
