### ISSUE TITLE
Create new tagged release for v1

### ISSUE THREAD

**Issue by gavrielrh** [reportportal/agent-python-pytest#235]
Hi 🙂
I was looking to use this library with pytest >= 5.4.0 (reportportal version < 5, so v1 branch) and ran into the same issue that was encountered in https://github.com/reportportal/agent-python-pytest/issues/165

I initially was going to submit a PR to fix this, but I noticed that it actually was fixed back in March:  [ea33cba6e074484f27b6afaa476670d1bbe75151](https://github.com/reportportal/agent-python-pytest/commit/ea33cba6e074484f27b6afaa476670d1bbe75151)

Would it be possible for y'all to bump the version number / create a new tagged release (on github & pypi) such that this fix will be available?

Thank you!

**Comment by iivanou** [comment]
Done.
