### ISSUE TITLE
Test execution is hanging there when try to send 2nd log 

### ISSUE THREAD

**Issue by leoyyoung** [reportportal/agent-python-pytest#249]
Hi

Currently I want to use agent-python-pytest with reportportal, and send logs to it also.
I followed the same example in the guide: https://github.com/reportportal/agent-python-pytest
But the test is hanged there while I try to send logs continously, see below:

Here is my test function:

    rp_logger.info("Test result for test_add_1")<<<Test Code will hang here, no errors displayed, this log is displayed in ReportPortal System
    rp_logger.info("This is test msg for RPLogger")

Hope to get comments&suggestions, Thanks

**Comment by iivanou** [comment]
Hi,

Could you provide environment details along with debug logs?
