### ISSUE TITLE
All test results are shown in the first test run when using the new version of pytest-reportportal

### ISSUE THREAD

**Issue by ohank** [reportportal/agent-python-pytest#251]
Same problem as:
https://github.com/reportportal/agent-python-pytest/issues/182

But now with the new version of pytest-reportportal 5.0.8 and reportportal-client 5.0.9
The long path that this creates when many tests are run somehow makes the database stopped working correctly.
The next test run doesn't show tests that have been run.

Example of how long path looks like but we get 500 .py files.
![image](https://user-images.githubusercontent.com/44366788/109304243-43745380-783c-11eb-943d-31ec40ea1007.png)

**Comment by iivanou** [comment]
@ohank Can you try changes from #252? It fixed the issue on my side.

**Comment by ohank** [comment]
The reproduce time is long so i will try when i can.
How do i get the chance?
Are it in any release?

**Comment by iivanou** [comment]
It's not released, you have to apply the change from the specified PR locally. It's gonna be released once you confirm that the change works for you.

**Comment by ohank** [comment]
Ok i will try it out in the comming week thanks for the fast respons 🙂

**Comment by Formartha** [comment]
please merge it, it works.
