### ISSUE TITLE
Connect RP logger to rootlogger

### ISSUE THREAD

**Issue by Formartha** [reportportal/agent-python-pytest#255]
Hi,

In our project we are overriding the root logger every test/fixture. the reason is that we are creating different segments and storing them to different locations.

Currently, I'm struggling to incorporate the report portal logger even using the fixture as listed. What I'm missing there?

It's not writing it to RP even when I was able to add the rp handler to the root logger.

Thanks

**Comment by iivanou** [comment]
By default logging to RP is disabled. You need to set the appropriate log level either via *.ini file(`rp_log_level = 'INFO'`) or via cmd line option.

**Comment by Formartha** [comment]
Tried it, but it's not working. I guess it's because we are overriding the default root logger.
The default pytest logging infrastructure should be enabled? if so, I'll have to fork out the project as we aren't using it (it's very limited if you'd ask me)

**Comment by iivanou** [comment]
> The default pytest logging infrastructure should be enabled?

Definitely. Look into [this](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/listener.py#L56) code.

**Comment by Formartha** [comment]
Okay,
Enabled it, but it still isn't working. is there a way to incorporate the RP logger w/o having the need to bond it to pytest logger?

**Comment by iivanou** [comment]
You can patch your logger the way it is done for the Pytest logger. It can be done much easier comparing to the current implementation in the agent.

**Comment by Formartha** [comment]
Was able to do it. can close the ticket.
I'll raise another question related to xdist and the hierarchy level
