### ISSUE TITLE
'reportportal_client.errors.ResponseError: 4001: Incorrect Request'

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#262]
Error appears during runnining tests with ReportPortal and the latest Pytest:

reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'name' should not contain only white spaces and shouldn't be empty. Field 'name' should have size from '1' to '256'.]

python 3.8.3
pytest-reportportal==5.0.8
pytest == 6.2.3

full log:
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\_pytest\main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Users\\.virtualenvs\r\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\\.virtualenvs\r\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pytest_reportportal\plugin.py", line 97, in pytest_sessionstart
INTERNALERROR>     session.config.py_test_service.start_launch(
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\pytest_reportportal\service.py", line 206, in start_launch
INTERNALERROR>     item_id = self.rp.start_launch(**sl_pt)
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\reportportal_client\service.py", line 237, in start_launch
INTERNALERROR>     self.launch_id = _get_id(r)
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\reportportal_client\service.py", line 68, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File "C:\Users\\.virtualenvs\\lib\site-packages\reportportal_client\service.py", line 100, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'name' should not contain only white spaces and shouldn't be empty. Field 'name' should have size from '1' to '256'.]

**Comment by iivanou** [comment]
@dkuchynskyi reportportal-client version? Debug logs, please. Steps/code to reporduce?

**Comment by dkuchynskyi** [comment]
Rebuild the whole environment fixed the problem
