### ISSUE TITLE
After upgrading to latest, second part of fixtures does not executed

### ISSUE THREAD

**Issue by bivas6** [reportportal/agent-python-pytest#265]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**

I have a pytest auto-use fixture, with a test scope (should be executed every test). 
It does some logic business before the test start, then yield, and after the test finishes it log with some attachments.
It works perfectly, until today, after upgrading to 5.0.9

**Steps to Reproduce**
1. create a conftest.py file, with fixture, for example:
```
@pytest.fixture(autouse=True)
def my_test_fixture(request):
    logger.info('before test')
    yield
    logger.info("After test...",
                    attachment={
                        "name": "attachment",
                        "data": <data>
                        "mime": "text/html"
                    })
```
             
2. run

**Expected behavior**
The log with the attachment after the `yield` statement should appear in the report-portal.

**Actual behavior**

This log and attachment does not appear

**Package versions**
Include version info of the following packages: reportportal-client, pytest-reportportal: 

reportportal-client: 5.0.9
pytest-reportportal: 5.0.9

**Additional context**

**Comment by iivanou** [comment]
@bivas6 From what version did you jump to 5.0.9? Have you tried updating reportportal-client? It's not the latest version.

**Comment by bivas6** [comment]
This is not a bug. 
I used to check if report-portal is enabled in a specific pytest run by testing if rp_launch is exists in the test config options.
This parameter is always return None now, so I changed the condition and it works as expected.

Thanks.
