### ISSUE TITLE
Test gets interrupted status on ReportPortal[v5]

### ISSUE THREAD

**Issue by leonardsaraujo** [reportportal/agent-python-pytest#266]
I'm having a problem with the tests status on ReportPortal.

Some tests have the status: interrupted

As shown in the images below.

![Capturar](https://user-images.githubusercontent.com/82540052/119655893-7492fe80-be00-11eb-8823-d5e024b41915.PNG)
![Capturar](https://user-images.githubusercontent.com/82540052/119656184-cb003d00-be00-11eb-96b5-4e89cd17d8f4.PNG)

**Comment by HardNorth** [comment]
@leonardsaraujo The latest version of `pytest` agent with all fixes is `5.0.10`, please update it.
