### ISSUE TITLE
"Skipped" tests in To Investigate even with rp_is_skipped_an_issue = False

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#275]
"Skipped" tests in To Investigate even with rp_is_skipped_an_issue = False
pytest-reportportal==5.0.10
pytest == 6.2.4

Added
rp_is_skipped_an_issue = False
setting doesn't work, all skiped tests added into the To Investigate section

**Comment by iivanou** [comment]
It was fixed in #267 .  Update both client and agent packages. If the issue still exists, then provide debug logs. Thanks,
