### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by Niccolum** [reportportal/agent-python-pytest#281]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I see test results without full code coverage in reportportal.

**Describe the solution you'd like**
If possible - check, if pytest-cov (most popular plugin for coverage) is installed and send coverage info to reportportal

**Comment by iivanou** [comment]
@Niccolum Are you sure the bug resides in the correct project? This one includes code coverage. 
![image](https://user-images.githubusercontent.com/8349078/133750807-d9e640cd-eea2-4d9e-850f-50c49d12fd3b.png)

**Comment by Niccolum** [comment]
@iivanou I don't know any developers, who use pytest without pytest-cov. It's like Django without DRF. Why not?

**Comment by iivanou** [comment]
I do not understand you. What the problem is? Coverage for this agent is generated via pytest-cov....

**Comment by Niccolum** [comment]
Is it possible to send result of pytest-cov to reportportal? This is my main point)

**Comment by iivanou** [comment]
What is the use case? The results reported by the pytest-cov will duplicate the results which are sent by the agent.

**Comment by Niccolum** [comment]
Hmm. Maybe it's my missing. I can't find this info in reportportal to create custom graphs

**Comment by iivanou** [comment]
@Niccolum Double-check where you added --reportportal arguments to your pytest execution or not. The results will be reported by the agent only if that argument is passed to the pytest.
