### ISSUE TITLE
401 Client Error: Unauthorized for url 

### ISSUE THREAD

**Issue by ramih-saferide** [reportportal/agent-python-pytest#284]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
When executing the project from Jenkins, I get the following output:
```shell
[INFO] >>>>>>>>>>>>>>                 Run pytest                 <<<<<<<<<<<<<<
[ERROR     42][pytest_reportportal.plugin] 401 Client Error: Unauthorized for url: http://<HOST>:8080/api/v1/project/<project_name>
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/<jenkins-preoject-name>/.venv/lib/python3.8/site-packages/pytest_reportportal/plugin.py", line 40, in check_connection
    resp.raise_for_status()
  File "/var/lib/jenkins/workspace/<jenkins-preoject-name>/.venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://<HOST>:8080/api/v1/project/<project_name>
```
but when I connect with ssh to the server with the same credentials and execute the exact pytest command, it runs without any issue,
I'm not sure where the issue occure.

**Package versions**
`pytest-reportportal==5.0.10`
`reportportal-client==5.0.12`

**Comment by HardNorth** [comment]
@ramih-saferide So because you have no idea what's happening you decided to put this on us?
Can't accept that. Either you provide detailed bug report either any such issue will be closed.
