### ISSUE TITLE
Remove `rp_ignore_errors` flag

### ISSUE THREAD

**Issue by HardNorth** [reportportal/agent-python-pytest#288]
We are reporting tool we should not fail by default.

**Comment by Ern-st** [comment]
@HardNorth it would still be nice to be able to set the flag… is it possible to revert this commit and instead set the value to `False` by default?

**Comment by HardNorth** [comment]
@Ern-st What is the reason? Other language implementations don't need it.

**Comment by Ern-st** [comment]
@HardNorth We've had some stability issues with our RP installation and it is crucial that out test suite is run every night, also on weekends when no-one can fix RP

**Comment by Ern-st** [comment]
@HardNorth ok, that's good to know 😄 

We've experienced some other issues with the 5.1.0 client so we're locking our dependency to 5.0.12 for now 🔒

**Comment by wtrwinberg** [comment]
Hi @HardNorth - An issue occuring after moving from 5.1.0 to 5.2.0 of the reportportal-client is PytestUnhandledThreadExceptionWarning trigger that didn't occur in version 5.1.0.

It states `AttributeError: 'NoneType' object has no attribute 'log'` when returning rp_client.log property within the __init__.py file located at the logs folder. It is warning, but does not break anything.

**Comment by Ern-st** [comment]
@HardNorth my colleague reported the issue and you've already fixed it ❤️  https://github.com/reportportal/client-Python/issues/182

**Comment by kisscelia** [comment]
We should delete this argument, in this repo file(examples-python -> pytest -> pytest.ini)

**Comment by HardNorth** [comment]
@kisscelia Done. Thanks for the notice.
