### ISSUE TITLE
How can I link test case id (from JIRA) to the reportportal?

### ISSUE THREAD

**Issue by zaneta500200** [reportportal/agent-python-pytest#297]
Hi,
I'd like to link test case id (from Jira) to test executions in reportportal but I can't find any info how to do it.
I tested `rp_issue_id_marks` but this is more suitable for bugs than test cases. Thanks in advance!

**Comment by iivanou** [comment]
@zaneta500200 You can wrap your test function with `@pytest.mark.tc_id('test_case')` and you will see `tc_id:test_case` among test tags in the RP UI.

**Comment by zaneta500200** [comment]
@iivanou thanks for quick response - I figured out the tag but it would be much more convenient to have it linked in the same way as bugs (issue egd-1234 on the print screen
![Zrzut ekranu 2022-02-04 114259](https://user-images.githubusercontent.com/31521085/152515978-f5a00e97-f42a-4f26-a380-fe32a8d17631.png)
)

**Comment by iivanou** [comment]
`@pytest.mark.tc_id(" [{tc_id}]({url})")`

**Comment by alphoense** [comment]
@iivanou hi, I'm working with @zaneta500200 on this problem.

Injecting such markup `[name](url)` works though for description but not for tags. (
We've tried to implement your suggestion with few modification, but everything we've got was plain url in tag on test (if solution was working)
We were trying to insert a html link as well, but so far all characters were escaped correctly from backed side on reportportal. and listed as a non-formatted text.

Our goal is to get such view:
![image](https://user-images.githubusercontent.com/7480823/152796775-fcb56e9e-57f9-4452-8352-01f25cf39f75.png)
this was modified on html page of the existing report.

Any other suggestion/tip that we can follow?

**Comment by iivanou** [comment]
We can implement passing `test_case_id` to the common client. The information about ID will be displayed the following way:
![image](https://user-images.githubusercontent.com/8349078/152979844-3d1444dc-76ad-4b8b-8f33-e4e2e0afdece.png)
Are u ok with that? The is no way to do it like for issues.

**Comment by HardNorth** [comment]
Implemented in: https://github.com/reportportal/agent-python-pytest/tree/5.1
