### ISSUE TITLE
Unknown config option: rp_issue_marks

### ISSUE THREAD

**Issue by kisscelia** [reportportal/agent-python-pytest#309]
**Describe the bug**

**Steps to Reproduce**
1. add this config to pytest.ini
2. run the tests

**Expected behavior**

**Actual behavior**
What actually happened.
![image](https://user-images.githubusercontent.com/13063673/174254874-f2cbbce1-7862-49ba-9f94-4b8b4c5e6f96.png)

**Package versions**
pytest                7.1.2
pytest-reportportal   5.1.1
reportportal-client   5.2.2

**Additional context**

**Comment by HardNorth** [comment]
The variable removed from examples and descriptions. Thank you!
