### ISSUE TITLE
An empty launch reported to ReportPortal when i run 'pytest ---collect-only'

### ISSUE THREAD

**Issue by MrTuzki** [reportportal/agent-python-pytest#31]
I think this is not what we expect.

My version:
python-reportportal   1.0.0
reportportal-client     3.0.0

**Comment by PositiveAlex** [comment]
Please provide here message about what do you expect

**Comment by krasoffski** [comment]
I think adding `rp_launch` option to config file was a bad idea. In my option it would be better to keep only CLI option `--rp-launch` which __always__ creates new launch in RP.

**Comment by s0undt3ch** [comment]
You have access to the pytest CLI arguments and options, perhaps look if  collect only option was passed and if not, then create a launch.

**Comment by krasoffski** [comment]
@s0undt3ch, thank you for idea! We try to do this.

**Comment by s0undt3ch** [comment]
If I be a few minutes today I'll get you a PR.
