### ISSUE TITLE
INTERNALERROR> KeyError: 'subTypes'

### ISSUE THREAD

**Issue by timqut** [reportportal/agent-python-pytest#314]
**Describe the bug**
reportportal-client    3.2.3
pytest-reportportal    1.0.9
7-21 9:05~ got below error, works fine more than 2years.

[Error] :

INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 194, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/plugin.py", line 45, in pytest_sessionstart
INTERNALERROR>     session.config.py_test_service.init_service(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/service.py", line 117, in init_service
INTERNALERROR>     self.issue_types = self.get_issue_types()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_reportportal/service.py", line 348, in get_issue_types
INTERNALERROR>     for item in self.project_settings["subTypes"][item_type]:
INTERNALERROR> KeyError: 'subTypes'

**[investigation]**

timq@timqumacp rcc_api_test % curl -X GET --header 'Authorization: bearer 09ff2efe-bc49-4138-b475-9aac45d64ace' http://qa-report.rccchina.com/api/v1/rcc_api_test/settings
{"statisticsStrategy":"STEP_BASED","project":"rcc_api_test","subTypes":{"TO_INVESTIGATE":[{"locator":"TI001","typeRef":"TO_INVESTIGATE","longName":"To Investigate","shortName":"TI","color":"#ffb743"}],"NO_DEFECT":[{"locator":"ND001","typeRef":"NO_DEFECT","longName":"No Defect","shortName":"ND","color":"#777777"}],"AUTOMATION_BUG":[{"locator":"AB001","typeRef":"AUTOMATION_BUG","longName":"Automation Bug","shortName":"AB","color":"#f7d63e"}],"PRODUCT_BUG":[{"locator":"PB001","typeRef":"PRODUCT_BUG","longName":"Product Bug","shortName":"PB","color":"#ec3900"}],"SYSTEM_ISSUE":[{"locator":"SI001","typeRef":"SYSTEM_ISSUE","longName":"System Issue","shortName":"SI","color":"#0274d1"}]}}%   timq@timqumacp rcc_api_test %

**Comment by HardNorth** [comment]
`pytest-reportportal` of version `1.0.9` was released more than 2 years ago. The artifact wasn't changed since then but the server was changed. And versions `1.*.*` was designed for Report Portal version 4 which is not supported anymore. So you have to update your library if you want to use it with the latest versions of Report Portal.
