### ISSUE TITLE
how to display grouped tests

### ISSUE THREAD

**Issue by pbezpal** [reportportal/agent-python-pytest#316]
Hello! I write tests with pytest and use the pytest-reportportal package for reporting in RP. Now my reports looked like
![My reports](https://automated-testing.info/uploads/default/original/2X/1/152e1c7488459dc6ce3a6bdefc3e1eede3e95773.png)

Is it possible to group tests so that the reports look like this
![Reports with group tests](https://automated-testing.info/uploads/default/original/2X/2/28077bb6d7a64d0eb90602e852a3246c12e2147f.png)

**Comment by HardNorth** [comment]
@pbezpal Checkout `rp_hierarchy_*` configuration parameters in our documentation: https://github.com/reportportal/agent-python-pytest#configuration
