### ISSUE TITLE
Common suite for tests(Xdist) 

### ISSUE THREAD

**Issue by ageleisha-ms** [reportportal/agent-python-pytest#318]
Hello, I want to clarify one moment about Xdist. Is it expected behavior when each Xdist worker creates its own suite?
RP - Build: 5.7.2

pytest-xdist==2.5.0
pytest==7.1.3
reportportal-client==5.2.5
pytest-reportportal==5.1.2

Additional settings:
rp_hierarchy_code = True
rp_hierarchy_dirs_level = 1

Run cmd: py.test  test_file.py --tx 2*popen --dist loadgroup --reportportal

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/91192984/195430923-1cdcd6a9-18cb-49df-9707-a69a781a8496.png">

Thanks.

**Comment by HardNorth** [comment]
Yes, it is expected, the same as for another property:
```
rp_hierarchy_dirs = True - Enables hierarchy for tests directories, default False. Doesn't support 'xdist' plugin.
```
