### ISSUE TITLE
Incorrect item name when running tests in nested folders

### ISSUE THREAD

**Issue by yakovbabich** [reportportal/agent-python-pytest#327]
**Describe the bug**

The name of an item is incorrect when tests running from different nested folders.

For example:
2 tests running, each in its folder ('goo' and 'zoo') when both folders under a root folder 'temp':
![image](https://user-images.githubusercontent.com/112324141/215749341-7f133a74-f18b-48f8-af22-c89f75c00cf8.png)

The name of the first item 'goo' is correct but the second item's name has an additional 'zoo' in it and an additional hierarchy folder:
![image](https://user-images.githubusercontent.com/112324141/215748473-3385e33a-9c97-42e4-96d8-f7f5dab888fe.png)

As can be seen in the picture above, the name is incorrect and should appear as: 'tests/temp/zoo/test_zoo.py', in which should be another item with the test's name.

**Steps to Reproduce**
To reproduce, create similar folder structure as shown in the image above, when there is a nested hierarchy of folders.

**Expected behavior**
A correct name should appear on all items.

**Actual behavior**
An incorrect name appear on item.

**Package versions**
pytest-reportportal==5.1.3

**Comment by HardNorth** [comment]
@yakovbabich, your issue missing significant data.
First of all, by default (without any flags) the agent reports tests in different format, like here:
![Screenshot 2023-02-17 at 5 20 58 PM](https://user-images.githubusercontent.com/4364466/219680565-cf4fb87b-f715-4786-ab89-bd790c8c386f.png)

So, I suppose you are using `rp_hierarchy_code` flag. But in this case everything works correct for me:
![Screenshot 2023-02-17 at 5 21 13 PM](https://user-images.githubusercontent.com/4364466/219680892-97aab545-02df-4cc0-86e2-afa4d540b365.png)

To remove any misunderstanding and save our both time, please provide an example project which reproduces the case, until then I count this issue as invalid.

**Comment by HardNorth** [comment]
Cannot reproduce
