### ISSUE TITLE
Include feature to exclude pytest marks

### ISSUE THREAD

**Issue by Sikamaru** [reportportal/agent-python-pytest#33]
Hi, during tests automation I've faced with small problem - all pytest marks are send to report portal as tags.
It's really useful feature but sometimes I use marks which I don't want to sent to RP: 
@pytest.mark.skip
@pytest.mark.usefixtures
@pytest.mark.xfail
and etc.

Could you think about this improvement?
Maybe it will be helpfull to add additional option in pytest.ini like rp_ignore_tags

**Comment by PositiveAlex** [comment]
I think it is good to have feature. 
So here we need to add this config option, update documentation and unit tests. 

You're welcome to create pull request for this!

**Comment by Sikamaru** [comment]
@PositiveAlex

I can try, but I'm not sure that my knowledge in python  will be enough for this)
