### ISSUE TITLE
Separate test stages when using steps

### ISSUE THREAD

**Issue by EyalrAtBay** [reportportal/agent-python-pytest#332]
Hi, I have been using the nested steps in test reporting and it works really well, I wanted to ask if there are any plans to incorporate different test stages, i.e "set up", "test body" etc..

Technically it would mean any fixtures/methods marked as a @step and run before the collected test would appear collectively under a step named "Set up" in the UI, all steps related to the actual test/s would appear under "Test body" and any steps run after the actual test/s would appear under the "Teardown" step. 

Allure has a similar functionality to further explain what I mean:
<img width="101" alt="image" src="https://user-images.githubusercontent.com/104712903/177032201-61455cf1-bcb2-4e02-b35f-d0dfa1d62cc2.png">

Appreciate your help and support.

**Comment by HardNorth** [comment]
@rplevka Not to  appropriate level, since pytest call these hook after it started a test only. So if there is no test, no such hooks would be called. And if there is several tests, then session fixture will be called for the first one in the test collection and for the last one.

**Comment by HardNorth** [comment]
Please use: https://github.com/reportportal/agent-python-pytest/releases/tag/5.4.3
