### ISSUE TITLE
Verify length of attribute value - Attribute value should have size from 1 to 128

### ISSUE THREAD

**Issue by ntkathole** [reportportal/agent-python-pytest#346]
https://github.com/reportportal/agent-python-pytest/blob/c20819d0acda7a193d5e74924e59d8db7c889ea5/pytest_reportportal/service.py#L625

Currently agent-python-pytest do not verify attribute value max length, which leads to a traceback at report portal side. 

As a part of solution, We can choose one of the option below :

- We need to verify length and ignore the attribute if len is greater than 128. 
- Trim the value to limit it to 128 chars.

Current workaround is to identify all bad attributes and set them as `rp_ignore_attributes`

**Comment by HardNorth** [comment]
Fixed in: https://github.com/reportportal/agent-python-pytest/releases/tag/5.3.0
