### ISSUE TITLE
Each test item has detailed logs in RP, but the launch lacks logs in LOG VIEW

### ISSUE THREAD

**Issue by SteffieLi** [reportportal/agent-python-pytest#352]
Hi,

After I used agent-python-pytest to import test results to report portal, for every launch in my RP project, there is no logs. 
<img width="1797" alt="image" src="https://github.com/reportportal/agent-python-pytest/assets/84319023/acf07e00-9b5f-4e0a-9df0-0829378c16cb">
But when I go to each test item, there are detailed logs. 
<img width="1789" alt="image" src="https://github.com/reportportal/agent-python-pytest/assets/84319023/1bdcb65a-9b52-4d87-abc2-d99d3ce9038b">

Is this normal? I'm not sure if there's a configuration setting I've set incorrectly.

Here is my pytest.ini:

> [pytest]
addopts = -v -s --capture=tee-sys
          -n 8 --dist=loadgroup --reruns 1
          --reportportal
          --headed --video on

> rp_uuid = fb586627-32be-47dd-93c1-678873458a5f
> rp_endpoint = http://192.168.1.10:8080
> rp_project = user_personal
> rp_launch = local - debug
> rp_ignore_attributes = 'usefixture'
> rp_is_skipped_an_issue = False
> rp_hierarchy_code = True
> rp_log_level = INFO

**Comment by HardNorth** [comment]
@SteffieLi Yes, it is expected. RP agents put logs to the corresponding item in which context they were reported. What makes you think different?

**Comment by SteffieLi** [comment]
I just thought that all logs would also be displayed at the launch level. Thanks!
