### ISSUE TITLE
how to change the Method Type in pytest agent?

### ISSUE THREAD

**Issue by tmax22** [reportportal/agent-python-pytest#355]
it is possible to specify in report portal method types like "Before Suite" or "After Methods" in frameworks like TestNG for java.

<img width="341" alt="image" src="https://github.com/reportportal/agent-python-pytest/assets/147702803/baeedebc-e8f8-4847-9fa2-432ae049bcae">

is it possible to set this method in pytest?

**Comment by HardNorth** [comment]
@tmax22 No `pytest` is not `TestNG`. Fixtures for `pytest` are generators and there is no direct mapping between `Test Suites` in `TestNG` and `scope=Session` in `pytest`.

To report fixtures in tests please use this version of `pytest`: https://github.com/reportportal/agent-python-pytest/releases/tag/5.4.3
And enable it with `rp_report_fixtures = True` in `pytest.ini` file.

**Comment by bybilo78** [comment]
@HardNorth Do you have an example how to use "rp_report_fixtures = True" for pytest? Must the fixtures be named in a special type?
