### ISSUE TITLE
Pls update the client version to 5.5.6 to fix issue with downloading large files

### ISSUE THREAD

**Issue by pavloshchepan** [reportportal/agent-python-pytest#370]
**Describe the bug**
Here is the explanation
https://github.com/reportportal/client-Python/issues/228

**Steps to Reproduce**
Send very large file for which RPResponse will be returned with an error

**Expected behavior**
Flow is not raising AttributeError: 'NoneType' error

**Actual behavior**
AttributeError: 'NoneType' object has no attribute 'messages' raised

**Package versions**
reportportal-client:5.5.4

**Comment by pavloshchepan** [comment]
Created pull request to fix the issue
https://github.com/reportportal/agent-python-pytest/pull/371

**Comment by HardNorth** [comment]
@pavloshchepan Please reinstall the agent it should pick the latest version.
