### ISSUE TITLE
why MAX_ITEM_NAME_LENGTH

### ISSUE THREAD

**Issue by MeitarR** [reportportal/agent-python-pytest#375]
I have 2 questions

1. why is `MAX_ITEM_NAME_LENGTH` hardcoded to `256`? If I patch it locally to something bigger, will it cause trouble to the backend?
2. if the answer to the first question is that it will be fine, then why isn't it an exported feature?

the reason I'm asking is that we have very long test names (together with parametrized) and most of the test names get cropped

**Comment by HardNorth** [comment]
Yes it's maximum length on server, if you patch it will cause failures on test upload.

**Comment by MeitarR** [comment]
> Yes it's maximum length on server, if you patch it will cause failures on test upload.

well, I can tell that a friend of mine tried to patch it and said that everything was fine.

Maybe there was confusion in the code?

looking at https://github.com/reportportal/commons-reporting/blob/develop/src/main/java/com/epam/ta/reportportal/ws/reporting/ValidationConstraints.java#L29 I see that 256 is the max for launch name, and the max for test item is 1024

**Comment by HardNorth** [comment]
@MeitarR Looks like I forgot we increased this value, OK I'll update it.

**Comment by HardNorth** [comment]
Please use: https://github.com/reportportal/agent-python-pytest/releases/tag/5.4.3

**Comment by MeitarR** [comment]
Looks like you didn't change the value from 256 😅

**Comment by HardNorth** [comment]
@MeitarR, yes, created a new release with this fix:
https://github.com/reportportal/agent-python-pytest/releases/tag/5.4.4
