### ISSUE TITLE
Exception when using RP with pytest (plugin version 5.4.5)

### ISSUE THREAD

**Issue by Formartha** [reportportal/agent-python-pytest#384]
Hello,
configured RP and it worked fine until I started getting this execption:

Logging error ---
07:47:51  Traceback (most recent call last):
07:47:51    File "/usr/local/lib/python3.10/site-packages/logstash_async/handler.py", line 162, in emit
07:47:51      data = self._format_record(record)
07:47:51    File "/usr/local/lib/python3.10/site-packages/logstash_async/handler.py", line 96, in _format_record
07:47:51      formatted = self.formatter.format(record)
07:47:51    File "/home/jenkins/agent/workspace/Automation-Content-Linux/automation/src/utils/parsers/logging_utils.py", line 75, in format
07:47:51      self._prefix_extra_record_fields_with_type(message)
07:47:51    File "/home/jenkins/agent/workspace/Automation-Content-Linux/automation/src/utils/parsers/logging_utils.py", line 94, in _prefix_extra_record_fields_with_type
07:47:51      elif isinstance(value, collections.Sequence):
07:47:51  AttributeError: module 'collections' has no attribute 'Sequence'
07:47:51  Call stack:
07:47:51    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
07:47:51      return _run_code(code, main_globals, None,
07:47:51    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
07:47:51      exec(code, run_globals)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
07:47:51      raise SystemExit(pytest.console_main())
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187, in console_main
07:47:51      code = main()
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 164, in main
07:47:51      ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
07:47:51      return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
07:47:51      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
07:47:51      res = hook_impl.function(*args)
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
07:47:51      return wrap_session(config, _main)
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 268, in wrap_session
07:47:51      session.exitstatus = doit(config, session) or 0
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 322, in _main
07:47:51      config.hook.pytest_runtestloop(session=session)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
07:47:51      return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
07:47:51      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
07:47:51      res = hook_impl.function(*args)
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
07:47:51      item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
07:47:51      return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
07:47:51      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
07:47:51      res = hook_impl.function(*args)
07:47:51    File "/usr/local/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 94, in pytest_runtest_protocol
07:47:51      self.runner.pytest_runtest_protocol(item, nextitem)
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
07:47:51      runtestprotocol(item, nextitem=nextitem)
07:47:51    File "/usr/local/lib/python3.10/site-packages/_pytest/runner.py", line 130, in runtestprotocol
07:47:51      reports.append(call_and_report(item, "call", log))
07:47:51    File "/usr/local/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 154, in call_and_report
07:47:51      hook.pytest_runtest_logreport(report=report)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
07:47:51      return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
07:47:51      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
07:47:51      res = hook_impl.function(*args)
07:47:51    File "/home/jenkins/agent/workspace/Automation-Content-Linux/automation/conftest.py", line 187, in pytest_runtest_logreport
07:47:51      logger.info(f"-- Test status: {report.outcome.upper()} --")
07:47:51    File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
07:47:51      self._log(INFO, msg, args, **kwargs)
07:47:51    File "/usr/local/lib/python3.10/site-packages/pytest_reportportal/rp_logging.py", line 134, in _log
07:47:51      return original_func(self, *args, **kwargs)
07:47:51    File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
07:47:51      self.handle(record)
07:47:51    File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
07:47:51      self.callHandlers(record)
07:47:51    File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
07:47:51      hdlr.handle(record)
07:47:51    File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
07:47:51      self.emit(record)
07:47:51    File "/usr/local/lib/python3.10/site-packages/logstash_async/handler.py", line 165, in emit
07:47:51      self.handleError(record)
07:47:51  Message: '-- Test status: PASSED --'
07:47:51  Arguments: ()

What should I do?

**Comment by HardNorth** [comment]
@Formartha, by this line: `07:47:51 File "/usr/local/lib/python3.10/site-packages/logstash_async/handler.py", line 165, in emit`, I see error happening in `python-logstash-async ` library, which we nothing to do. Why this happens I don't really know, library's error message says nothing about that.

Please ask for help library's developers directly here: https://github.com/eht16/python-logstash-async
