### ISSUE TITLE
How to attach issue to report portal issuing marker

### ISSUE THREAD

**Issue by Formartha** [reportportal/agent-python-pytest#388]
Hello,

I have a usercase where I want to use my codebase to generate/link bugs properly to report portal.
I'm unable to do it and I would like to ask for help.

That's what I have now in my source code
![image](https://github.com/user-attachments/assets/0399db67-13ab-4716-92e4-02facaf684f8)
 
 That's what I want to happen but happening incorrectly:
![image](https://github.com/user-attachments/assets/b16bbf7e-7c3e-4828-aab9-d1e5b6e323e2)

**Comment by HardNorth** [comment]
@Formartha To do this you need to specify `rp_bts_project` and `rp_bts_url` in your configuration parameters, see here: https://reportportal.io/docs/log-data-in-reportportal/test-framework-integration/Python/pytest/

**Comment by Formartha** [comment]
@HardNorth , now it's not reporting..
I used the same URL and Project from the jira cloud plugin and it's not reporting the issue to RP.

What should be done next?

**Comment by HardNorth** [comment]
@Formartha I missed another one parameter, which you need to specify: `rp_bts_issue_url`

**Comment by Formartha** [comment]
works now! but it still add this commend of the bug ID, why?

**Comment by HardNorth** [comment]
@Formartha That's how it was originally designed.

**Comment by Formartha** [comment]
What's the incentive? can we reconsider it?

**Comment by HardNorth** [comment]
@Formartha Practically, no. This was years ago.

**Comment by DzmitryHumianiuk** [comment]
@Formartha,  

The issue at the top is just an attached object to the defect type.  
It can be sent as an additional request to the API, or potentially even included as part of the main request.  

If I understand correctly, the question is whether this functionality should be integrated into the standard **python-client**?
