### ISSUE TITLE
no stacktrace for failed tests

### ISSUE THREAD

**Issue by SergeyPirogov** [reportportal/agent-python-pytest#4]

**Comment by avarabyeu** [comment]
Have it fixed?

**Comment by krasoffski** [comment]
Exception is posted but as log message, stack trace contain un-formatted line.
![image](https://cloud.githubusercontent.com/assets/1073415/25763386/7a489f88-31eb-11e7-863b-bfa050d8dd71.png)

**Comment by DzmitryHumianiuk** [comment]
_component:ui_

will be fixed with 3.0.3
