### ISSUE TITLE
Test Errors not being reported

### ISSUE THREAD

**Issue by s0undt3ch** [reportportal/agent-python-pytest#44]
Test errors are apparently not being reported.
Latest stable release of the client and the master branch tip for the pytest plugin.

Found out about this while running into a too many open files issue.

I'll post more info when I'm at my laptop.

**Comment by ailjushkin** [comment]
Hi thanks, please attach additional info about 

- version
- use case
- actual error stacktrase
- environment

 etc. what you will need to explain more precisely, thanks
