### ISSUE TITLE
Unable to run example test using Python 2.7.12

### ISSUE THREAD

**Issue by krasoffski** [reportportal/agent-python-pytest#45]
### Steps for reproduce:
 1. Following steps from README.rst install `pip install pytest_reportportal`. 
 2. Than create `sample_test.py` from readme file and `pytest.ini` configuration file.
 3. Run test with command `pytest sample_test.py`.

There are no any issues with `Python3`. But with `Python2` you might get following issue:
```
 $ pytest sample_test.py 
=============================== test session starts ================================
platform linux2 -- Python 2.7.12, pytest-3.2.0, py-1.5.2, pluggy-0.4.0
rootdir: /ReportPoral, inifile: pytest.ini
plugins: reportportal-1.0.1
collected 1 item s

sample_test.py F

===================================== FAILURES =====================================
_____________________________________ test_one _____________________________________

    def test_one():
>       logger.info("Case1. Step1")

sample_test.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/logging/__init__.py:1167: in info
    self._log(INFO, msg, args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pytest_reportportal.rp_logging.RPLogger object at 0x7f31745b5c10>
level = 20, msg = 'Case1. Step1', args = (), exc_info = None, extra = None
stack_info = False, attachment = None

    def _log(self, level, msg, args,
             exc_info=None, extra=None, stack_info=False, attachment=None):
        """
            Low-level logging routine which creates a LogRecord and then calls
            all the handlers of this logger to handle the record.
            """
        sinfo = None
        if logging._srcfile:
            # IronPython doesn't track Python frames, so findCaller raises an
            # exception on some versions of IronPython. We trap it here so that
            # IronPython can use logging.
            try:
>               fn, lno, func, sinfo = self.findCaller(stack_info)
E               TypeError: findCaller() takes exactly 1 argument (2 given)

agent-python-pytest/pytest_reportportal/rp_logging.py:23: TypeError
============================= 1 failed in 0.07 seconds =============================
```

The root cause is obvious - different semantics of internal `logging` methods. 
Need to investigate changes which lead to this problem.

**Comment by yehonadav** [comment]
you can replace RPLogger with this code to run in python 2 for the time being

import sys
import logging

from pytest_reportportal.service import PyTestService


class RPLogger(logging.getLoggerClass()):
    def __init__(self, name, level=0):
        super(RPLogger, self).__init__(name, level=level)

    def _log(self, level, msg, args,
             exc_info=None, extra=None, stack_info=False, attachment=None):
        """
        Low-level logging routine which creates a LogRecord and then calls
        all the handlers of this logger to handle the record.
        """
        if logging._srcfile:
            # IronPython doesn't track Python frames, so findCaller raises an
            # exception on some versions of IronPython. We trap it here so that
            # IronPython can use logging.
            try:
                fn, lno, func = self.findCaller()
            except ValueError:  # pragma: no cover
                fn, lno, func = '(unknown file)', 0, '(unknown function)'
        else:
            fn, lno, func = '(unknown file)', 0, '(unknown function)'

        if exc_info and not isinstance(exc_info, tuple):
            exc_info = sys.exc_info()

        record = self.makeRecord(
            self.name, level, fn, lno, msg, args, exc_info, func, extra
        )
        record.attachment = attachment
        self.handle(record)


class RPLogHandler(logging.Handler):
    # Map loglevel codes from `logging` module to ReportPortal text names:
    _loglevel_map = {
        logging.NOTSET: 'TRACE',
        logging.DEBUG: 'DEBUG',
        logging.INFO: 'INFO',
        logging.WARNING: 'WARN',
        logging.ERROR: 'ERROR',
        logging.CRITICAL: 'ERROR',
    }
    _sorted_levelnos = sorted(_loglevel_map.keys(), reverse=True)

    def __init__(self, level=logging.NOTSET):
        super(RPLogHandler, self).__init__(level)

    def emit(self, record):
        msg = ''

        try:
            msg = self.format(record)
        except (KeyboardInterrupt, SystemExit):
            raise
        except Exception:
            self.handleError(record)

        for level in self._sorted_levelnos:
            if level <= record.levelno:
                break

        return PyTestService.post_log(
            msg,
            loglevel=self._loglevel_map[level],
            attachment=record.__dict__.get('attachment', None),
        )

**Comment by krasoffski** [comment]
Need new release for this. Closed!
