### ISSUE TITLE
Separate all test by modules in report portal

### ISSUE THREAD

**Issue by flyAwayGG** [reportportal/agent-python-pytest#47]
**Enhancement**
Now result of each test in suite is writed directly to one launch in report portal (All > Pytest Launch > All tests). It would be good to add some separation by modules and fixtures. Like this: All > Pytest Launch > tests/path.py > test_name (and think about > fixtures of test and test)

**Comment by evjlobanova** [comment]
@flyAwayGG hi! 
The launch structure is Launch> Suite> Test> Step.  
Could you please give more details about this issue?

**Comment by s0undt3ch** [comment]
I've been working on this but the way reportportal_client is coded, ie, its stack, its proving hard to achieve this.
Its not impossible but we need to keep a separate stack and the way pytest allows you to have multiple class nesting for test "suites" makes it even harder...

**Comment by s0undt3ch** [comment]
I honestly have no clue how to report fixtures, what's the mapping for that on the report portal API side?

**Comment by krasoffski** [comment]
Keeping internal stack is not only python client. Most of other clients use the similar approach (it is some kind of report portal requirements).

**Comment by s0undt3ch** [comment]
https://github.com/reportportal/agent-python-pytest/pull/62
