### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'py_test_service' coming while deactivate pytest_reportportal plugin

### ISSUE THREAD

**Issue by vaibhavrastogi1988** [reportportal/agent-python-pytest#57]
I am getting following error when i would like to temporary disable integrations with Report Portal just deactivate pytest_reportportal plugin with command: `py.test -p no:pytest_reportportal ./tests`

I am currently running this with Python 3.6 and the latest pytest.
```
Trace:
request = <SubRequest 'rp_logger' for <Function 'test_one'>>
```
```
    @pytest.fixture(scope="function")
    def rp_logger(request):
        import logging
        # Import Report Portal logger and handler to the test module.
        from pytest_reportportal import RPLogger, RPLogHandler
        # Setting up a logging.
        logging.setLoggerClass(RPLogger)
        logger = logging.getLogger(__name__)
        logger.setLevel(logging.DEBUG)
```
```
        # Create handler for Report Portal.
>       rp_handler = RPLogHandler(request.node.config.py_test_service)
E       AttributeError: 'Config' object has no attribute 'py_test_service'
```

**Comment by hemantsk** [comment]
You can do this if you don't want to report with `-p no:pytest_reportportal` and use StreamHandler for printing in console stdout with -s option. 
```python
if hasattr(request.node.config, 'py_test_service'):
    rp_handler = RPLogHandler(request.node.config.py_test_service)
else:
    rp_handler = logging.StreamHandler(sys.stdout)
```
Attribute Error can be avoided and cases with -p or without -p can be handled.

**Comment by DzmitryHumianiuk** [comment]
@vaibhavrastogi1988 resolved?
can be closed?

**Comment by kleptog** [comment]
I think this should be added to the example in the README.

**Comment by DzmitryHumianiuk** [comment]
@kleptog can you plz send pull request with it?

**Comment by DzmitryHumianiuk** [comment]
@hemantsk pull request into readme.md?

**Comment by iivanou** [comment]
README has been updated in #129 . Closed.
