### ISSUE TITLE
Is it possible to make report portal ignore skip tests ?

### ISSUE THREAD

**Issue by iShimon** [reportportal/agent-python-pytest#58]
when building my run i mark some test to be skipped but all the skipped test are going into report portal ... it will be very useful to tell the agent not to pass skipped tests

**Comment by DzmitryHumianiuk** [comment]
@iShimon you mean, no to send skipped items into ReportPortal?

**Comment by iShimon** [comment]
@DzmitryHumianiuk Yes , i'm trying to make my skipped tests not to appear on the portal with no success

**Comment by DzmitryHumianiuk** [comment]
@iShimon this can be done on side of your code.
just update the method, which sends events `onSkipped` status

i'm not a python dev, but i guess it's somewhere here:
https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/listener.py#L37

you can also join you slack, find python channel and ask guys who use this integration

**Comment by kleptog** [comment]
This is how we fixed it in our code. Just place this in a conftest.py somewhere where pytest will find it. Hope this helps.

```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):
    """ ReportPortal considers "skip" to be a failure, which is stupid, so
    we convert it to a pass (of course only when reportportal is active) """

    outcome = yield
    if item.config.pluginmanager.has_plugin('pytest_reportportal') and \
            item.config.option.rp_launch:
        try:
            outcome.get_result()
        except pytest.skip.Exception:
            outcome.force_result([])
```

**Comment by DzmitryHumianiuk** [comment]
@iShimon let us know, does it work for you

**Comment by kleptog** [comment]
Just to let you know, I found a corner case where this doesn't work. Namely, if you want to skip an entire class, like so:

```
@pytest.mark.skip
class TestFoo(TestCase)
    def test_foo(self):
        pass
```

Fortunately this doesn't happen often (for obvious reasons).

**Comment by iShimon** [comment]
I actually didn't choose this way , I change the listener because I did a custom conftest.py file this solution doesn't now work for me , but it look like a very "clean" way to do it

**Comment by DzmitryHumianiuk** [comment]
@iShimon with 5.0 we plan to introduce configurable configuration.

**Comment by kleptog** [comment]
FWIW, my above solution breaks things inside pytest. By raising a skip not all of the setup of a test is executed, yet by marking it "passed" it tries to actually run the test, which leads to strange errors. Ultimately I think patching the agent is the best way to go.

**Comment by iShimon** [comment]
yes exactly what i did , i would upload the patch buy i think best thing is to wait for the configurable configuration version. since patching will need to re-register the pytest plugin
