### ISSUE TITLE
Specifying launch tags from command line?

### ISSUE THREAD

**Issue by KyleMagocs** [reportportal/agent-python-pytest#59]
Is there any reason the plugin doesn't support this?  I can draw up a pull request real quick but I figured if it wasn't already an option, there must be a reason for it, right?

**Comment by krasoffski** [comment]
Hi, 
It seem like no one thinks about this. You are welcome to create PR.

**Comment by rplevka** [comment]
do this using native pytest `-o` argument:
```
  -o OVERRIDE_INI, --override-ini=OVERRIDE_INI
                        override ini option with "option=value" style, e.g.
                        `-o xfail_strict=True -o cache_dir=cache`.
```

so you'll get something like:
```
py.test -o rp_launch=yourlaunchanme
```

**Comment by DzmitryHumianiuk** [comment]
@KyleMagocs does comment about resolves your issue?

**Comment by DzmitryHumianiuk** [comment]
@rplevka could you plz send it as PR into readme file for agent?

**Comment by vkolgi** [comment]
#93 I have raised the PR updating the README.

**Comment by rplevka** [comment]
@DzmitryHumianiuk I believe you can close this now
