### ISSUE TITLE
Enable implicit plugin usage by using a `--reportportal` flag

### ISSUE THREAD

**Issue by liiight** [reportportal/agent-python-pytest#64]
Instead of activation the plugin by default and using pytest's disable plugin ability to shut it down, it would be nicer to enable it explicitly by sending a `--reportportal` flag:
`pytest tests --reportportal`
Which can also be used in the pytets.ini files:
```
[pytest]
addopts: --reportportal
```
If i'll have the time I'll try to push a PR with this change myself

**Comment by evjlobanova** [comment]
@liiight  hello, unfortunately now we do not have any python specialist in a team. So feel free to send a pull request, or you can post this issue in our slack chat https://reportportal.slack.com/messages/C9PMAA690, maybe someone from community can help you

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors what do you think?

**Comment by DzmitryHumianiuk** [comment]
@krasoffski @s0undt3ch 
@ramriddick @frizzby @vakulich @KKoukiou 
@sivashh @kleptog 
@aliaksandr-trush 
what do you think?

**Comment by aliaksandr-trush** [comment]
I vote to not implement this behavior.
1. I do not see benefits.
2. I think we need to have as less actions as possible for client activation.

**Comment by KKoukiou** [comment]
@liiight I don't see any reason for this change, can you please elaborate why you find it better?

Also ``` pytest --trace-config``` for searching active plugins will give invalid results if we make this change, no?

**Comment by liiight** [comment]
The benefit is that after installing the plugin it is invoked by default on every run, crashing if config isn't correct.

Explicit is better than implicit...

**Comment by s0undt3ch** [comment]
I'm not opposed to this change in behavior. Usually we want to *enable* report portal on some circumstances, CI, not all.

**Comment by abotalov** [comment]
I think it would be better to solve such issues in general way on Pytest side.

Recently ability to disable plugin autoloading was added to Pytest - https://github.com/pytest-dev/pytest/pull/3787. Then you probably should be able to explicitly load them using `pytest_plugins` variable or `PYTEST_PLUGINS` env variable.

**Comment by DzmitryHumianiuk** [comment]
@sivashh 

> Here you have most of properties available through both cli and pytest.ini. Cli options override ini options.

this is how we make it for Java client.
initially agent search for System level variables, then override it by `reportportal.property` file variables, and then override it with command line variables.

this helps to manage execution combinations in CI, by enabling/disabling adapter, send it to debug, or change launch name, or tags, based on enviroment

**Comment by kleptog** [comment]
The way I fixed this in our CI tests is using the feature merged in master where reportalplugin only works if the configuration is complete. In my case I comment out the rp_endpoint configuration in the checked in code and the use the pytest "-o" option to activate reportalporal only for the CI.

This patch would remove the need for that hack, but I guess opinions will differ as to whether it's a hack or not.

**Comment by aliaksandr-trush** [comment]
@liiight I see benefits now.
I've created PR. Please review it and approve that it is what you mean.

**Comment by DzmitryHumianiuk** [comment]
@liiight @aliaksandr-trush accepted. merged
