### ISSUE TITLE
Attachment files just showing up as txt and does not show the name of the file attached

### ISSUE THREAD

**Issue by Preyansh91** [reportportal/agent-python-pytest#69]
When we attach a file to report portal logs, it only show up as TXT and does not show file name give. It creates a lot of problem when attaching multiple files.

rp_logger.info(
        "Oprofile report",
        attachment={
            "name": "opreport",
            "data": r.content,
            "mime": "application/octet-stream",
        },
    )

**Comment by krasoffski** [comment]
As I remember this behavior is not specific for python library but Report Portal itself.

**Comment by evjlobanova** [comment]
@Preyansh91  hi! we have the same issue in #338 . We plan its implementation after version 5

**Comment by evjlobanova** [comment]
close as duplicate
