### ISSUE TITLE
Nested hierarchy test items is hardcoded to standard pytest python/unittest

### ISSUE THREAD

**Issue by ringods** [reportportal/agent-python-pytest#73]
For a customer, I wrote 2 custom pytest plugins. Each of these plugins contain custom Python subclasses of `pytest.File`, `pytest.Collector` and `pytest.Item` to create a nested tree of test suites and tests.

When using `pytest-reportportal`, this nested structure is flattened in ReportPortal. When looking at the code, I see explicit references to `pytest.Class`, `pytest.Function` and alike in the support for nesting. This limits the nesting only to pytests using the standard `python` or `unittest` plugins.

Please make `pytest-reportportal` agnostic to which plugin(s) generate test items: you should process the tree as returned by any possible pytest plugin.

Note: IDEs like `PyCharm` show the nested hierarcy returned by my pytest plugins correctly.

**Comment by aliaksandr-trush** [comment]
Probably it should be fixed by https://github.com/reportportal/agent-python-pytest/pull/62
Need to release new agent version and verify
