### ISSUE TITLE
pytest.mark.skipif fixture should be handled properly

### ISSUE THREAD

**Issue by aliaksandr-trush** [reportportal/agent-python-pytest#76]
If we have test marked with pytest.mark.skipif we can mark tests as No Defect and add defect comment from "reason" parameter.

**Comment by DzmitryHumianiuk** [comment]
@aliaksandr-trush is it proposal?
Question or statement?

**Comment by aliaksandr-trush** [comment]
@DzmitryHumianiuk proposal

**Comment by vkolgi** [comment]
I will detail this issue since there is not much discussion here. pytest's skipif mark skips if the certain condition is true and prints out the "reason" that is specified. So the OP wants to set the defect label to be set from reason attribute. While this is something we have done internally for ourselves, for the plugin it comes down to what other client libraries(for java, js) are doing. If this behavior is uniform across, then I can raise a PR for the same, or if this behavior needs to be a configuration as well, we can have a look at.

**Comment by DzmitryHumianiuk** [comment]
@vkolgi it would be nice, if you can send us PR with this change. And i would agree, that it should be a part of configuration

**Comment by HardNorth** [comment]
@aliaksandr-trush @vkolgi I'm not really getting what would you like to see. Could you please elaborate it?
I understand that some time passed by already, but now we want to close all longstanding issues.

For those who would like to use `skipif` pytest feature I created an example: https://github.com/reportportal/examples-python/blob/master/pytest/tests/test_skip_condition.py

And there is possible to use `rp_is_skipped_an_issue = False` parameter if someone doesn't want to se "To Investigate" mark.

**Comment by HardNorth** [comment]
Abandoned

**Comment by kiransk77** [comment]
Hi @HardNorth I've faced the same issue with the skipif as mentioned by @aliaksandr-trush.
If I add the below two lines in the test case
request.node.add_marker(pytest.mark.issue(reason="This is not a defect", issue_type="ND"))
pytest.skip("This is not a defect")

This is the view in the report portal
![image](https://github.com/user-attachments/assets/006a538d-51c5-4390-93b6-84ca3dba75c8)
It clearly displays the No Defect label and also the reason below it. 

But if i use skipif decorator like
@pytest.mark.skipif(platform.system().lower() == 'windows', reason="This is not a defect")
Then this is the view
![image](https://github.com/user-attachments/assets/9fe2f0b6-e713-4114-af5b-3761d912d163)
We have to open the test result and check the logs to know the reason for failure
![image](https://github.com/user-attachments/assets/6333f662-376d-474a-b086-deaae70b911c)

Having some 200 test cases skipped would require the user to open each one to figure out the reason for skipping. Then as @aliaksandr-trush mentioned If we have test marked with pytest.mark.skipif, we can mark tests as No Defect and add defect comment from "reason" parameter.

**Comment by kiransk77** [comment]
> I will detail this issue since there is not much discussion here.
> 
> pytest's skipif mark skips if the certain condition is `true` and prints out the "_reason_" that is specified.
> 
> So the OP wants to set the defect label to be set from reason attribute. While this is something we have done internally for ourselves, for the plugin it comes down to what other client libraries (for java, js) are doing. If this behavior is uniform across, then I can raise a PR for the same, or if this behavior needs to be a configuration as well, we can have a look at.

Hey @vkolgi I need this implementation, can you share it with me or guide me through it?

**Comment by HardNorth** [comment]
@kiransk77 We have `@pytest.mark.issue` decorator and pytest has `@pytest.mark.skipif` decorator, these are two different decorators serving different purpose. I'm not going to mix their functionality. If you see they both do not work together, this might be an issue, please pos a separate issue if this is true.
