### ISSUE TITLE
Uploading of test results should be done after the test run

### ISSUE THREAD

**Issue by ringods** [reportportal/agent-python-pytest#79]
So far, I have not been able to use `pytest-reportportal` agent successfully. After thorough investigation, I noticed that our testsuite uses `patch` in a few cases for `builtin.open` and `requests` library. When this is done, it has an impact on the workings of the async RP service object which pushes results to the server.

To work around this, pushing the results should only be done after the test suite has ran and all the `patch` setups are cleaned up.

**Comment by osherdp** [comment]
@ringods, can you provide a sample code that reproduces this problem? I think I got it, but I just want to make sure We're solving the right problem.

The feature of "offline update" is probably needed regardless, for example when running tests in parallel. So I'm currently looking into it.

**Comment by HardNorth** [comment]
Abandoned
