### ISSUE TITLE
rp_ignore_errors doesn't apply on session start

### ISSUE THREAD

**Issue by rplevka** [reportportal/agent-python-pytest#83]
if there is some issue with the report portal from the very beginning (not reachable, access denied, etc.),
the `rp_ignore_errors` does not stop the py.test from crashing miserably.

the `plugin.py` hook: `pytest_sessionstart(session)`  initializes the service (`session.config.py_test_service.init_service()`)

and calls its `start_launch()` straight away. - one could possibly catch the `HTTP` error exception at this point and call `pytest_unconfigure(session.config)`, but this does not throw the exception straight away since it calls some async method (it just adds it to the queue).

**Comment by DzmitryHumianiuk** [comment]
@rplevka 
>if there is some issue with the report portal from the very beginning (not reachable, access denied, etc.)
you mean server here?

**Comment by rplevka** [comment]
@DzmitryHumianiuk - yes.
I mean `rp_endpoint` - I'd like to make the use of the rp_logger not critical to the py.test run

**Comment by rplevka** [comment]
I think this got pretty much solved by bringing in the explicit plugin calling using `--reportportal` option.
this pretty much makes user to explicitly say: "i want to use the report portal" and if something is not right with the connection etc., it is just okay to fail.
