### ISSUE TITLE
[regression] pytest now crashes if pytest-xdist is used

### ISSUE THREAD

**Issue by rplevka** [reportportal/agent-python-pytest#87]
this got introduced by 
https://github.com/reportportal/agent-python-pytest/commit/d625655003a9f09b0a3b5e72120673de352e6fd9

```
INTERNALERROR>   File "/home/rplevka/work/rplevka/agent-python-pytest/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/home/rplevka/work/rplevka/agent-python-pytest/pytest_reportportal/service.py", line 202, in start_pytest_item
INTERNALERROR>     part = self._start_stack.pop(0)
INTERNALERROR> IndexError: pop from empty list
```

```python
    def start_pytest_item(self, test_item=None):
        self._stop_if_necessary()
        print(test_item)
        print(self._start_stack)
        if self.RP is None:
            return

        while True:
            part = self._start_stack.pop(0)                    #<- apparently this is mepty from the beginning, as the collect_tests seems to be skipped
            if part is test_item:
                break
            payload = { 
                'name': self._get_item_name(part),
                'description': self._get_item_description(part),
                'tags': self._get_item_tags(part),
                'start_time': timestamp(),
                'item_type': 'SUITE'
            }
            log.debug('ReportPortal - Start Suite: request_body=%s', payload)
            self.RP.start_test_item(**payload)
....
```

**Comment by DzmitryHumianiuk** [comment]
@rplevka plz send a pull request with a fix

**Comment by rplevka** [comment]
@bigbZik - hey, any idea how could we fix this properly?
the thing is [this](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/plugin.py#L95) will skip the collection part for the non-master instances (slaves) and thus the `_start_stack` stays unpopulated for the slave workers.

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors

**Comment by bigbZik** [comment]
> 
> 
> @bigbZik - hey, any idea how could we fix this properly?
> the thing is [this](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/plugin.py#L95) will skip the collection part for the non-master instances (slaves) and thus the `_start_stack` stays unpopulated for the slave workers.

Originally issue was added with more earlier [change](https://github.com/reportportal/agent-python-pytest/commit/0122f1967b641d65d842b5aa00a2f09b6048dbcd). @s0undt3ch 
I guess hierarchy should be disabled in distributed mode. I'm working on fix.

**Comment by s0undt3ch** [comment]
What reports back to RP when using xdist, the slaves? The master node?
We shouldn't prevent xdist usage but how badly would it be to allow collection to happen on the slave side. Would the order be the same?
Could we just allow collection to happen if it's a xdist node?

Maybe it's a safe bet to just don't allow hierarchical reporting when xdist is involved or if proves to be too much effort.

I really can't go any deeper than this right now. The implementation of RP on our company is now stalled and waiting for RP 4.5 or 5, the one which switches backend to PostgreSQL....

**Comment by rplevka** [comment]
@s0undt3ch 
You have the same chain of thoughts as I had. I tried to simply remove the "is_master" conditional around test collection to see how it goes - it worked, but it created some duplicates around classes. What's more there were some nesting issues - the hierarchy became something like:`launch->module->[class1]->[test1, test2 -> class1 -> test3]`.
I found that weird and backed out from doing this as the rabbit hole apparently goes deeper :)

- perhaps the logic of creating the test items needs to be expanded in a way that we first check, whether the item already exists (and if so - use it) before we create it?

Anyway, i believe that `xdist` slaves all do the full collection, the master then just orchestrates the execution by instructing them to execute specific tests by pointing to their indices.
( see 
https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md )

Perhaps enabling collection of items for slaves is the way, but I feel quite incompetent on the topic, that's why i asked the orig. contributor for a help as it seems he knew his stuff :)

**Comment by bigbZik** [comment]
@rplevka Did you try on newest build? Do you see error?

**Comment by rplevka** [comment]
> @rplevka Which version of pytest_reportportal can I use to avoid this error?
@tayalakansh unfortunately, there was no release after a [workaround commit](https://github.com/reportportal/agent-python-pytest/commit/492cdf1962bc01f4a8e12313944e2f4fa6f8cde8) got merged, so if you want to get this in, you should install from git repo's master branch

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors folks,
what steps required to make it released?

**Comment by rplevka** [comment]
@DzmitryHumianiuk not sure what your internal release guidelines are, but technically you navigate to the releases tab and hit "draft a new release"

**Comment by DzmitryHumianiuk** [comment]
@rplevka not sure it automated )

@ch-t was it automated so far?

**Comment by JMoravec** [comment]
I'm not sure if anyone else has had this issue, but I kept seeing the following error when attempting to run with xdist parallel: `INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'listener'`

I fixed this by changing the `pytest_configure_node` code in plugin.py to the following
```
@pytest.mark.optionalhook
def pytest_configure_node(node):
    if node.config._reportportal_configured is False:
        # Stop now if the plugin is not properly configured
        return
    if node.config.py_test_service.RP is None:
        node.config.py_test_service.init_service(
            project=node.config.getini('rp_project'),
            endpoint=node.config.getini('rp_endpoint'),
            uuid=node.config.getini('rp_uuid'),
            log_batch_size=int(node.config.getini('rp_log_batch_size')),
            ignore_errors=bool(node.config.getini('rp_ignore_errors')),
            ignored_tags=node.config.getini('rp_ignore_tags'),
            verify_ssl=node.config.getini('rp_verify_ssl')
        )
node.slaveinput['py_test_service'] = pickle.dumps(node.config.py_test_service)
```

I'm not sure if this is the correct fix or not (I'm not familiar with xdist or pytest plugins that much), but it seems related to this Github Issue

**Comment by iivanou** [comment]
I have not noticed any issues using the xdist plugin with the latest version of the agent.
