### ISSUE TITLE
py.test --reportportal ./tests/test_flight.py fails, So does pytest --tests-per-worker 2 --reportportal

### ISSUE THREAD

**Issue by shrinivasbb** [reportportal/agent-python-pytest#89]
Below are the failure logs, Creates a launch in the report portal but tests are not executed and launch does not end:

C:\Users\sb\PycharmProjects\pyTest1>py.test --reportportal ./tests/test_flight.py
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: C:\Users\sb\PycharmProjects\pyTest1, inifile: pytest.ini
plugins: xdist-1.23.0, rerunfailures-4.1, reportportal-1.0.4, parallel-0.0.3, metadata-1.7.0, html-1.19.0, forked-0.2, concurrent-0.1.2, allure-pytest-2.5.1
collecting 0 items
DevTools listening on ws://127.0.0.1:12593/devtools/browser/fd6154c2-e371-4f69-a097-503b9795f29f
collected 1 item
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 215, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pytest_concurrent.py", line 126, in pytest_runtestloop
INTERNALERROR>     _run_items(mode=mode, items=ungrouped_items, session=session, workers=workers)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pytest_concurrent.py", line 164, in _run_items
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pytest_reportportal\listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "c:\users\sb\appdata\local\programs\python\python37-32\lib\site-packages\pytest_reportportal\service.py", line 194, in start_pytest_item
INTERNALERROR>     part = self._start_stack.pop(0)
INTERNALERROR> IndexError: pop from empty list

**Comment by bigbZik** [comment]
See #87

**Comment by shrinivasbb** [comment]
Using pytest-parallel not pytest-xdist.

**Comment by bigbZik** [comment]
Did it work before with RP on your setup?

**Comment by krasoffski** [comment]
Existing fix for `xdist` uses internal implementation of master slave of `xdist`. It seems for me that it did not work with `pytest-parallel` before but not sure. Need to dive into `pytest-parallel` internals for more details.

**Comment by shrinivasbb** [comment]
Well, I am using pytest to run selenium tests. Since pytest-parallel is thread-safe it is recommended for selenium tests and pytest-xdist is not thread safe.

@bigbZik it never worked with pytest-parallel. But my RP setup is flawless, able to update test runs using TestNG java

**Comment by ringods** [comment]
I tested 1.0.4 of this pytest plugin, but also get the error `IndexError: pop from empty list` consistently. I do *not* have `pytest-parallel` or `pytest-xdist`. I do have a custom written plugin for my own test collection, but this follows the pytest callback very meticulously.

**Comment by HardNorth** [comment]
Done in: https://github.com/reportportal/agent-python-pytest/tree/5.1
