### ISSUE TITLE
Unable to see any launch results for the project

### ISSUE THREAD

**Issue by KaterynaStreltsovaDevPro** [reportportal/agent-python-pytest#98]
I have followed the instructions to configure the test framework, but still unable to see any launch results in the portal. Attempted to use IP and domain name, put ini file in different places, with no luck. 

The instance with portal is pingable and POST/GET  requests are successful from the terminal. Screenshot with the automation project structure has been attached.
Please suggest how to solve the issue.
Python 3.7, pytest package 4.0.0

<img width="664" alt="screen_1" src="https://user-images.githubusercontent.com/38039414/48662611-1b0e2400-ea8d-11e8-9395-3a08c3147825.png">

**Comment by rplevka** [comment]
@KaterynaStreltsovaDevPro, are  you sure you execute py.test command with `--report-portal` argument? If you don't specify it, the `pytest_reportportal` plugin won't be used.

**Comment by KaterynaStreltsovaDevPro** [comment]
@rplevka I used --reportportal as it's mentioned in official documentation for Python Pytest. 
Should I use --report-portal instead?

**Comment by rplevka** [comment]
@KaterynaStreltsovaDevPro sorry, no. your version was correct. I just had that from a top of my head.
Well. perhaps if you can paste some logs from a simple py.test session, it might show us some clues.

All I can advise now is to make sure that the API token you use is indeed valid and belongs to a user who really is assigned to the project and has the proper permissions (anyway, it should fail if it does not). do you also use `rp_ignore_errors`?

**Comment by KaterynaStreltsovaDevPro** [comment]
@rplevka  I have removed ini file and tried to pass the parameters via command line.
This is how the tests started:
--tests=" -s -vv tests\api_tests\accounts\auth\my_test.py --alluredir allure_report --reportportal --rp.endpoint xxx.xxx.8.xxx:8080 --rp.uuid exxxx-84a0-46df-97e3-xx --rp.project smoke_wlapi 
--rp_ignore_errors True"   --env=local --provider=ripple

Pytest arguments from above for pytest.main:
['-s', '-vv', 'tests\\api_tests\\accounts\\auth\\my_test.py', '--alluredir', 'allure_report_ripple', '--reportportal', '--rp.endpoint', 'xxx.xxx.8.xxx:8080', '--rp.uuid', 'xxxxx-84a0-46df-97e3-xxxxe5c', '--rp.project', 'smoke_wlapi', '--rp_ignore_errors', 'True']

I have an error 
error: unrecognized arguments: --rp.endpoint xxx.xxx.8.xxx:8080 --rp.uuid xxxxx-84a0-46df-97e3-xxxxe5c --rp.project smoke_wlapi --rp_ignore_errors True

It looks for me that the library can't parse the arguments

**Comment by KaterynaStreltsovaDevPro** [comment]
Well, I tried to plugin logger from the example and have error in lines      rp_handler = RPLogHandler(request.node.config.py_test_service)
E       AttributeError: 'Config' object has no attribute 'py_test_service'

**Comment by rplevka** [comment]
uset underscores instead of dots in the param names: `--rp_project` instaedo fo `--rp.project`, etc.

**Comment by KaterynaStreltsovaDevPro** [comment]
With underscores still have unrecognized arguments error: --rp_endpoint, etc

**Comment by rplevka** [comment]
Uh. Are yoy sure the pytest-reportportal is installed? Is your IDE using the right virtual environment? Can you see the rp_* otions in the `py.test --help`?

**Comment by KaterynaStreltsovaDevPro** [comment]
I have created a simple project for test purposes, pytest-reporting portal 1.0.4 and reporting-client 3.2.0 are installed on virtual env. RP options are available in help, however it still says 'unrecognized arguments'. Please see the attachment
![portal_screen](https://user-images.githubusercontent.com/38039414/49068945-b8591d00-f230-11e8-9b62-1a48028eeb0b.png)

**Comment by KaterynaStreltsovaDevPro** [comment]
Hi guys, do you have an idea what is going wrong above?

**Comment by iivanou** [comment]
@KaterynaStreltsovaDevPro 
These arguments must be defined in the pytest.ini file. If you want to overwrite arguments from that file, you can do it with the help of -o option like -o "rp_endpoint=YOUR_ENDPOINT".
